const translations = {
  "zh-Hant": {
    "meta.description": "OPC Osaka Gateway 是大阪精品 OPC 公司與多產業事業的入口網站。",
    "nav.group": "集團",
    "nav.ventures": "事業",
    "nav.registration": "登記",
    "nav.competitors": "競品",
    "nav.cases": "案例",
    "nav.lines": "路線",
    "nav.systems": "系統",
    "nav.diary": "日記",
    "nav.contact": "下一步",
    "hero.eyebrow": "大阪精品 OPC 事業入口",
    "hero.lead": "為 OPC Osaka Group 建立清晰、具精品感的入口：連結多產業事業、AI 營運、市場研究與部署系統。",
    "hero.primary": "查看事業方向",
    "hero.secondary": "查看內部系統",
    "signal.baseLabel": "據點",
    "signal.base": "日本大阪",
    "signal.roleLabel": "角色",
    "signal.role": "集團入口",
    "signal.focusLabel": "重點",
    "signal.focus": "AI 原生營運",
    "group.eyebrow": "集團定位",
    "group.title": "以大阪為基地，建立跨產業的精品營運集團。",
    "group.body": "OOG 是未來大阪公司架構的公開入口：以一個母品牌承接多個產業專案，並共享策略、研究、自動化與數位部署的營運層。",
    "ventures.ai.title": "AI 營運",
    "ventures.ai.body": "代理人治理、訊號到行動流程，以及內部自動化模板。",
    "ventures.market.title": "市場情報",
    "ventures.market.body": "針對 CDP、客戶互動與意圖資料市場建立競品研究儀表板。",
    "ventures.education.title": "教育與人才",
    "ventures.education.body": "學校平台、招募流程、學生入口，以及跨境人才系統。",
    "ventures.commerce.title": "商務系統",
    "ventures.commerce.body": "庫存、加盟、餐飲服務、進出口貿易，以及真實企業使用的輕量營運工具。",
    "registration.eyebrow": "日本登記事業項目",
    "registration.title": "將進出口貿易納入大阪公司的事業目的。",
    "registration.body": "OOG 的事業範圍除了 AI、網站、資料分析、展示平台與教育內容，也保留未來做跨境商品、設備、數位產品與品牌代理的彈性。日本公司登記時，可用較寬但清楚的日文事業目的描述。",
    "registration.trade.label": "登記建議",
    "registration.trade.jp": "各種商品の輸出入、販売、卸売、小売及び代理店業務",
    "registration.trade.note": "對應繁中：各類商品之進出口、銷售、批發、零售及代理業務。",
    "registration.digital.label": "延伸方向",
    "registration.digital.jp": "デジタルコンテンツ、ソフトウェア、教育教材及び関連商品の企画、制作、販売、輸出入及びライセンス業務",
    "registration.digital.note": "讓網站、軟體、教材、展示內容與跨境銷售能放在同一個公司目的下。",
    "cases.eyebrow": "已完成案例",
    "cases.title": "第一個完成案例：OOG 多語系入口網站。",
    "cases.intro": "這個案例證明 OOG 不只是概念，而是已經能完成從命名、內容整理、GitHub 版本管理到 Render 公開部署的完整流程。",
    "cases.case1.status": "已完成",
    "cases.case1.title": "OPC Osaka Gateway 官方入口",
    "cases.case1.body": "建立一個可供股東、合作夥伴與內部成員查看的公開網站，支援繁體中文、日文、簡體中文與英文，並透過 GitHub 與 Render 建立可持續更新的部署流程。",
    "cases.case1.scopeLabel": "範圍",
    "cases.case1.scope": "品牌入口、四語內容、公司日記、公開部署",
    "cases.case1.stackLabel": "工具",
    "cases.case1.resultLabel": "成果",
    "cases.case1.result": "形成可展示、可追蹤、可持續擴充的公司入口。",
    "cases.case2.status": "已確認四語上線",
    "cases.case2.title": "Exhibit Platform 展示平台",
    "cases.case2.body": "完成一個已上線的展示平台，並確認繁體中文、日文、簡體中文與英文四語版本可公開瀏覽。此案例可作為 OOG 對外展示多語系網站部署與營運能力的完成作品。",
    "cases.case2.scopeLabel": "範圍",
    "cases.case2.scope": "展示平台、四語上線、公開網址驗證",
    "cases.case2.linkLabel": "網址",
    "cases.case2.resultLabel": "成果",
    "cases.case2.result": "形成第二個可公開展示的完成案例。",
    "cases.case3.status": "已上線",
    "cases.case3.title": "Intex Osaka Exhibitions 展覽平台",
    "cases.case3.body": "建立以大阪展覽活動為主題的公開展示平台，並完成 Render 線上部署。此案例補足 OOG 在活動資訊、展覽導覽與地區型內容網站上的可交付能力。",
    "cases.case3.scopeLabel": "範圍",
    "cases.case3.scope": "大阪展覽資訊、公開展示頁、Render 部署驗證",
    "cases.case3.linkLabel": "網址",
    "cases.case3.resultLabel": "成果",
    "cases.case3.result": "形成第三個可公開展示的完成案例。",
    "cases.case4.status": "教學頁已上線 / 影片待補",
    "cases.case4.title": "Stock Bot 投資計畫教學",
    "cases.case4.body": "建立投資計畫教學入口，讓使用者可從繁體中文版本開始理解投資計畫流程、操作步驟與平台功能。目前頁面已公開上線，但教學影片尚未完成，後續需要補上影片腳本、錄製與嵌入。",
    "cases.case4.scopeLabel": "範圍",
    "cases.case4.scope": "投資計畫教學頁、繁中入口、Render 部署驗證、影片待補",
    "cases.case4.linkLabel": "網址",
    "cases.case4.resultLabel": "成果",
    "cases.case4.result": "形成第四個可公開展示的案例；影片完成後再升級為完整教學案例。",
    "cases.case5.status": "已上線",
    "cases.case5.title": "Japan FB Tracker 寵物廠商追蹤",
    "cases.case5.body": "建立日本展覽與廠商資訊追蹤入口，協助整理寵物相關廠商、展會線索與後續開發名單，作為 OOG 在產業資料蒐集與商務開發上的公開案例。",
    "cases.case5.scopeLabel": "範圍",
    "cases.case5.scope": "寵物廠商追蹤、展會線索、公開資料入口",
    "cases.case5.linkLabel": "網址",
    "cases.case5.resultLabel": "成果",
    "cases.case5.result": "形成第五個可公開展示的完成案例。",
    "cases.case6.status": "已上線",
    "cases.case6.title": "Asia Pet Export Hub 寵物出口平台",
    "cases.case6.body": "建立亞洲寵物產品出口與廠商資訊平台，補足 OOG 在跨境商品、寵物產業與進出口貿易方向上的可展示成果。",
    "cases.case6.scopeLabel": "範圍",
    "cases.case6.scope": "寵物產品出口、亞洲廠商資訊、跨境商務入口",
    "cases.case6.linkLabel": "網址",
    "cases.case6.resultLabel": "成果",
    "cases.case6.result": "形成第六個可公開展示的完成案例。",
    "cases.case7.status": "已上線",
    "cases.case7.title": "Japan Seafood Hub 水產廠商平台",
    "cases.case7.body": "建立日本水產廠商與商務資訊入口，作為 OOG 在水產產業、供應商整理與進出口貿易方向上的公開展示案例。",
    "cases.case7.scopeLabel": "範圍",
    "cases.case7.scope": "水產廠商資訊、供應商整理、跨境商務入口",
    "cases.case7.linkLabel": "網址",
    "cases.case7.resultLabel": "成果",
    "cases.case7.result": "形成第七個可公開展示的完成案例。",
    "lines.eyebrow": "四條事業線",
    "lines.title": "把七個案例整理成四條可對外說明的事業線。",
    "lines.body": "OOG 目前不只是作品列表，而是逐步形成可營運的商務組合：展示平台負責對外呈現與活動入口；投資教育保留教學型產品線；寵物出口與水產貿易則對應進出口貿易與供應商整理。",
    "lines.exhibit.title": "展示平台",
    "lines.exhibit.body": "將 OOG 官方入口、Exhibit Platform 與 Intex Osaka Exhibitions 統一歸入展示平台線，主軸是多語網站、活動展示、企業入口與公開部署。",
    "lines.invest.title": "投資教育",
    "lines.invest.body": "將 Stock Bot 投資計畫教學歸入投資教育線，定位為金融知識、學習入口與操作教學，不碰投資顧問或金融商品交易業務。",
    "lines.pet.title": "寵物出口",
    "lines.pet.body": "將 Japan FB Tracker 與 Asia Pet Export Hub 歸入寵物出口線，用於整理寵物廠商、展會線索、亞洲供應商與跨境商務開發。",
    "lines.seafood.title": "水產貿易",
    "lines.seafood.body": "將 Japan Seafood Hub 歸入水產貿易線，作為水產供應商整理、商務資訊入口與未來進出口合作開發的基礎。",
    "systems.eyebrow": "內部系統",
    "systems.title": "從概念到可部署的公司基礎設施。",
    "systems.site": "供股東、合作夥伴與內部成員使用的公開入口。",
    "systems.deploy": "可重複使用的 GitHub、Render 與靜態研究頁部署流程。",
    "systems.research": "用於平台定位與策略判斷的競爭情報儀表板。",
    "diary.eyebrow": "建立日記",
    "diary.title": "把每一次決策、部署與定位修正留下紀錄。",
    "diary.intro": "OOG 的日記不是行銷文章，而是公司從零開始建立時的工作紀錄：命名、網站、部署、多語系、事業定位與下一步策略，都會在這裡逐步整理。",
    "diary.entry1.month": "2026 / 06",
    "diary.entry1.title": "OOG 入口網站完成第一階段上線。",
    "diary.entry1.body": "今天確認 OOG 作為 OPC Osaka Gateway 的公開入口，並完成 GitHub 與 Render 部署。網站已支援繁體中文、日文與簡體中文，方便股東、合作夥伴與未來大阪法人相關成員查看。這一階段的核心不是把公司包裝得很大，而是先建立一個可信、可持續更新、能承接後續事業資訊的乾淨入口。",
    "diary.entry1.point1": "完成 OOG 命名與公開網址。",
    "diary.entry1.point2": "建立 GitHub 到 Render 的部署流程。",
    "diary.entry1.point3": "確立大阪精品 OPC 公司、多產業事業與 AI 營運層的初步定位。",
    "diary.entry2.month": "2026 / 06",
    "diary.entry2.title": "補強日本登記事業目的與進出口貿易方向。",
    "diary.entry2.body": "今日確認 OOG 網站已納入日本公司登記可用的事業目的文字，並將進出口貿易補進商務系統與登記區塊。這讓大阪法人未來除了 AI、網站、資料分析、展示平台與教育內容，也能保留跨境商品、數位產品、教材與品牌代理的營運彈性。",
    "diary.entry2.point1": "完成：確認進出口貿易與日文登記文字已出現在公開網站。",
    "diary.entry2.point2": "待補：Stock Bot 教學影片仍需腳本、錄製與嵌入。",
    "diary.entry2.point3": "下一步：將登記事業目的交由日本司法書士或行政書士確認正式送件文字。",
    "diary.entry3.month": "2026 / 06",
    "diary.entry3.title": "成功案例擴充到七個，並完成大區塊字體優化。",
    "diary.entry3.body": "今日確認 OOG 已新增三個公開案例：Japan FB Tracker、Asia Pet Export Hub 與 Japan Seafood Hub。案例區塊從原本四個擴充到七個，補強寵物廠商、寵物出口與水產廠商三條跨境商務線。同時完成大標題、案例卡、系統區塊與日記內容的字體比例調整，讓公開網站在大面積閱讀時更穩定、正式。",
    "diary.entry3.point1": "完成：新增三個產業案例並確認正式站已顯示連結。",
    "diary.entry3.point2": "待補：Stock Bot 教學影片仍需完成，Japan FB Tracker 的實際頁面標題也需後續校正。",
    "diary.entry3.point3": "下一步：持續整理跨境寵物、水產與進出口貿易案例，讓 OOG 的商務方向更清楚。",
    "diary.entry4.month": "2026 / 06",
    "diary.entry4.title": "完成公開站巡檢，確認七個案例與字體版本維持穩定。",
    "diary.entry4.body": "今日進行 OOG 例行維護檢查，確認 GitHub gh-pages 分支與 Render 正式站仍維持最新版本。網站目前保留七個完成案例、CDP 競品資料庫、日本登記事業目的、進出口貿易方向與優化後的大區塊字體樣式。今日沒有新增大型功能，因此以維護紀錄為主，確保股東與合作夥伴看到的是穩定版本。",
    "diary.entry4.point1": "完成：檢查 OOG 案例區、日記區、字體樣式與部署來源仍正常。",
    "diary.entry4.point2": "待補：Stock Bot 教學影片、Japan FB Tracker 實際頁面標題、登記事業目的正式審核仍需後續處理。",
    "diary.entry4.point3": "下一步：把跨境寵物、水產與進出口貿易案例整理成更清楚的商務路線圖。",
    "diary.entry5.month": "2026 / 06",
    "diary.entry5.title": "月末維護巡檢，整理 OOG 下一步商務路線。",
    "diary.entry5.body": "今日進行 OOG 月末維護檢查，確認公開站仍維持七個案例、CDP 競品資料庫、日本登記事業目的、進出口貿易方向與科技感字體版本。最近沒有新增大型功能，因此本日重點放在狀態整理：網站已具備對股東展示的基礎內容，下一步需要把跨境寵物、水產與進出口貿易案例整理成可執行的商務路線圖。",
    "diary.entry5.point1": "完成：確認正式站內容、部署來源與核心區塊維持穩定。",
    "diary.entry5.point2": "待補：Stock Bot 教學影片、Japan FB Tracker 頁面標題、登記事業目的正式審核仍未完成。",
    "diary.entry5.point3": "下一步：把七個案例分成展示平台、投資教育、寵物出口與水產貿易四條可對外說明的事業線。",
    "diary.entry6.month": "2026 / 06",
    "diary.entry6.title": "四條事業線正式上線，七個案例完成策略歸類。",
    "diary.entry6.body": "今日確認 OOG 正式站已新增「四條事業線」區塊，將七個案例整理為展示平台、投資教育、寵物出口與水產貿易。這讓網站從案例展示進一步變成事業架構說明，股東與合作夥伴可以更快理解 OOG 的商務方向、交付能力與未來可擴充的營運線。",
    "diary.entry6.point1": "完成：四條事業線區塊已部署，並同步繁中、日文、簡中、英文內容。",
    "diary.entry6.point2": "待補：Stock Bot 教學影片、Japan FB Tracker 頁面標題、登記事業目的正式審核仍需處理。",
    "diary.entry6.point3": "下一步：為四條事業線補上更具體的收益模式、目標客群與優先開發順序。",
    "diary.entry13.month": "2026 / 09",
    "diary.entry13.title": "持續追蹤雲端案例，OOG 主站與五個公開服務保持正常。",
    "diary.entry13.body": "今日完成 OOG 例行維護，確認首頁 3D Gateway、四條事業線、七個案例資料、競品資料庫及四語內容沒有異常。主站與五個公開案例正常回應；Intex Osaka Exhibitions 與 Japan FB Tracker 連續巡檢仍逾時，目前列為待恢復服務，OOG 主站及其他案例不受影響。",
    "diary.entry13.point1": "完成：檢查 GitHub gh-pages、Render 正式站、首頁介面、案例與競品資料。",
    "diary.entry13.point2": "待補：追蹤兩個逾時案例，完成 Stock Bot 教學影片、Japan FB Tracker 標題與日本登記事業目的審核。",
    "diary.entry13.point3": "下一步：把四條事業線轉成九月可執行清單，先定義收費方案與首批目標客戶。",
    "diary.entry12.month": "2026 / 09",
    "diary.entry12.title": "完成每日雲端巡檢，核心入口與五個案例回應正常。",
    "diary.entry12.body": "今日確認 OOG 正式站、首頁 3D Gateway、四條事業線、七個案例資料與 CDP 競品資料庫維持完整，最近 24 小時沒有新增重大功能。OOG 與五個案例網址成功回應；Intex Osaka Exhibitions 與 Japan FB Tracker 在本次 15 秒巡檢中逾時，先列入持續觀察，不影響 OOG 主站使用。",
    "diary.entry12.point1": "完成：驗證主站、四語資料、案例區、競品區與 GitHub 至 Render 的部署狀態。",
    "diary.entry12.point2": "待補：持續檢查兩個逾時案例，並完成 Stock Bot 教學影片、Japan FB Tracker 標題與日本登記事業目的正式審核。",
    "diary.entry12.point3": "下一步：整理四條事業線的九月執行順序，優先補上可收費服務與目標客戶。",
    "diary.entry11.month": "2026 / 09",
    "diary.entry11.title": "完成九月首輪維護，確認 OOG 雲端入口與事業內容持續穩定。",
    "diary.entry11.body": "今日檢查 OOG 最近 24 小時的版本、介面與部署狀態，期間沒有新增重大功能。首頁 3D Gateway、四條事業線、七個完成案例、CDP 競品資料庫與四語內容均維持完整，GitHub gh-pages 與 Render 正式站的發布流程也保持正常。",
    "diary.entry11.point1": "完成：巡檢首頁介面、案例連結、競品內容、多語資料與雲端部署來源。",
    "diary.entry11.point2": "待補：Stock Bot 教學影片、Japan FB Tracker 頁面標題及日本登記事業目的正式審核仍待完成。",
    "diary.entry11.point3": "下一步：為四條事業線建立可對外說明的客群、收入模式與九月執行優先序。",
    "diary.entry10.month": "2026 / 08",
    "diary.entry10.title": "完成例行雲端巡檢，確認首頁 3D 動畫與核心內容維持穩定。",
    "diary.entry10.body": "今日檢查 OOG 最近 24 小時的網站與部署狀態，未發現新的重大功能變動。GitHub gh-pages 分支、Render 正式站、首頁 3D Gateway 動畫、四條事業線、七個完成案例與 CDP 競品資料庫均維持正常，四語內容也保持一致，供股東與合作夥伴持續查閱。",
    "diary.entry10.point1": "完成：確認 GitHub、Render、首頁 3D 動畫、案例區與競品資料庫均可正常顯示。",
    "diary.entry10.point2": "待補：Stock Bot 教學影片、Japan FB Tracker 頁面標題及日本登記事業目的正式審核仍待完成。",
    "diary.entry10.point3": "下一步：補強四條事業線的目標客戶、收入模式與優先開發順序。",
    "diary.entry9.month": "2026 / 07",
    "diary.entry9.title": "持續維護四條事業線與七個案例，確認正式站狀態穩定。",
    "diary.entry9.body": "今日確認 OOG 公開站內容仍維持四條事業線、七個完成案例、CDP 競品資料庫與多語版本一致，沒有新增大型功能。這篇日記主要是做例行維護紀錄，讓股東與合作夥伴看到的正式版本保持一致、清楚且可追蹤。",
    "diary.entry9.point1": "完成：檢查首頁、四條事業線、案例區與日記區的顯示狀態。",
    "diary.entry9.point2": "待補：Stock Bot 教學影片、Japan FB Tracker 頁面標題、登記事業目的正式審核仍待完成。",
    "diary.entry9.point3": "下一步：補強各事業線的收益模式、客群定位與對外說明順序。",
    "diary.entry8.month": "2026 / 07",
    "diary.entry8.title": "完成四條事業線後，進行第一輪穩定維護紀錄。",
    "diary.entry8.body": "今日確認 OOG 的公開站仍維持四條事業線、七個完成案例、CDP 競品資料庫與多語版本內容一致。今天沒有新增大型功能，重點是把剛完成的事業線整理成可持續追蹤的狀態，讓股東與合作夥伴看到的是同一個穩定版本。",
    "diary.entry8.point1": "完成：檢查四條事業線、案例區與日記區在正式站上顯示正常。",
    "diary.entry8.point2": "待補：Stock Bot 教學影片、Japan FB Tracker 頁面標題、登記事業目的正式審核仍待完成。",
    "diary.entry8.point3": "下一步：為四條事業線補上更清楚的收益模式、目標客群與優先順序。",
    "diary.entry7.month": "2026 / 07",
    "diary.entry7.title": "月初穩定維護，確認四條事業線與七個案例維持完整。",
    "diary.entry7.body": "今日進行 OOG 月初維護巡檢，確認公開站仍維持四條事業線、七個完成案例、CDP 競品資料庫、日本登記事業目的與進出口貿易方向。近期沒有新增大型功能，因此本日以穩定狀態紀錄為主，確保股東與合作夥伴看到的是同一個清楚版本。",
    "diary.entry7.point1": "完成：確認正式站內容、導覽、案例與字體樣式都維持正常。",
    "diary.entry7.point2": "待補：Stock Bot 教學影片、Japan FB Tracker 頁面標題、登記事業目的正式審核仍未完成。",
    "diary.entry7.point3": "下一步：為四條事業線補上更明確的收益模式、目標客群與優先順序。",
    "contact.eyebrow": "下一步",
    "contact.title": "把這裡作為對外清楚、乾淨的公司入口。",
    "contact.body": "隨著 OPC Osaka Group 的架構逐步具體化，可將各事業、儀表板、股東頁面與內部工具集中放在這裡。"
  },
  ja: {
    "meta.description": "OPC Osaka Gateway は、大阪を拠点とするブティック型 OPC 企業と複数事業の入口サイトです。",
    "nav.group": "グループ",
    "nav.ventures": "事業",
    "nav.registration": "登記",
    "nav.competitors": "競合",
    "nav.cases": "実績",
    "nav.lines": "事業線",
    "nav.systems": "システム",
    "nav.diary": "日記",
    "nav.contact": "次の一手",
    "hero.eyebrow": "大阪発ブティック OPC 事業ゲートウェイ",
    "hero.lead": "OPC Osaka Group のための、品位ある明快な入口。複数事業、AI オペレーション、市場調査、デプロイ基盤をひとつのハブにつなぎます。",
    "hero.primary": "事業領域を見る",
    "hero.secondary": "内部システムを見る",
    "signal.baseLabel": "拠点",
    "signal.base": "日本・大阪",
    "signal.roleLabel": "役割",
    "signal.role": "グループ入口",
    "signal.focusLabel": "重点",
    "signal.focus": "AI ネイティブ運営",
    "group.eyebrow": "グループ定位",
    "group.title": "大阪を拠点に、複数産業へ展開するブティック型運営グループを構築します。",
    "group.body": "OOG は、将来の大阪法人構造に向けた公開ゲートウェイです。ひとつの親ブランドの下で複数の産業プロジェクトを束ね、戦略、調査、自動化、デジタルデプロイを共通の運営層として整えます。",
    "ventures.ai.title": "AI オペレーション",
    "ventures.ai.body": "エージェント管理、シグナルから実行までのワークフロー、社内自動化テンプレート。",
    "ventures.market.title": "市場インテリジェンス",
    "ventures.market.body": "CDP、顧客エンゲージメント、インテントデータ市場に向けた競合調査ダッシュボード。",
    "ventures.education.title": "教育・人材",
    "ventures.education.body": "学校プラットフォーム、採用フロー、学生ポータル、越境人材システム。",
    "ventures.commerce.title": "商務システム",
    "ventures.commerce.body": "在庫、フランチャイズ、フードサービス、輸出入貿易、実店舗で使える軽量な運営ツール。",
    "registration.eyebrow": "日本での登記事業目的",
    "registration.title": "輸出入貿易を大阪法人の事業目的に含めます。",
    "registration.body": "OOG は AI、ウェブサイト、データ分析、展示プラットフォーム、教育コンテンツに加えて、将来的な越境商品、設備、デジタル製品、ブランド代理にも対応できる余地を持たせます。日本での会社設立時には、広くても明確な事業目的として記載できます。",
    "registration.trade.label": "登記案",
    "registration.trade.jp": "各種商品の輸出入、販売、卸売、小売及び代理店業務",
    "registration.trade.note": "繁体字中国語の意味：各種商品の輸出入、販売、卸売、小売、代理業務。",
    "registration.digital.label": "拡張領域",
    "registration.digital.jp": "デジタルコンテンツ、ソフトウェア、教育教材及び関連商品の企画、制作、販売、輸出入及びライセンス業務",
    "registration.digital.note": "ウェブ、ソフトウェア、教材、展示コンテンツ、越境販売を同じ会社目的の中で扱えるようにします。",
    "cases.eyebrow": "完了事例",
    "cases.title": "最初の完了事例：OOG 多言語ゲートウェイサイト。",
    "cases.intro": "この事例は、OOG が単なる構想ではなく、名称設計、コンテンツ整理、GitHub でのバージョン管理、Render での公開デプロイまでを一貫して実行できることを示しています。",
    "cases.case1.status": "完了",
    "cases.case1.title": "OPC Osaka Gateway 公式入口",
    "cases.case1.body": "株主、パートナー、社内メンバーが確認できる公開サイトを構築。繁体字中国語、日本語、簡体字中国語、英語に対応し、GitHub と Render による継続更新可能なデプロイ手順を整えました。",
    "cases.case1.scopeLabel": "範囲",
    "cases.case1.scope": "ブランド入口、4言語コンテンツ、会社日記、公開デプロイ",
    "cases.case1.stackLabel": "ツール",
    "cases.case1.resultLabel": "成果",
    "cases.case1.result": "表示、追跡、継続拡張ができる会社の入口を形成。",
    "cases.case2.status": "4言語公開確認済み",
    "cases.case2.title": "Exhibit Platform 展示プラットフォーム",
    "cases.case2.body": "公開済みの展示プラットフォームを完成し、繁体字中国語、日本語、簡体字中国語、英語の4言語版が閲覧できることを確認しました。OOG が多言語サイトのデプロイと運営能力を対外的に示す完成事例です。",
    "cases.case2.scopeLabel": "範囲",
    "cases.case2.scope": "展示プラットフォーム、4言語公開、公開URL確認",
    "cases.case2.linkLabel": "URL",
    "cases.case2.resultLabel": "成果",
    "cases.case2.result": "公開表示できる2つ目の完了事例を形成。",
    "cases.case3.status": "公開済み",
    "cases.case3.title": "Intex Osaka Exhibitions 展示プラットフォーム",
    "cases.case3.body": "大阪の展示会・イベント情報をテーマにした公開展示プラットフォームを構築し、Render でのオンラインデプロイを完了しました。OOG がイベント情報、展示会ナビゲーション、地域型コンテンツサイトを納品できることを示す事例です。",
    "cases.case3.scopeLabel": "範囲",
    "cases.case3.scope": "大阪展示会情報、公開展示ページ、Render デプロイ確認",
    "cases.case3.linkLabel": "URL",
    "cases.case3.resultLabel": "成果",
    "cases.case3.result": "公開表示できる3つ目の完了事例を形成。",
    "cases.case4.status": "ページ公開済み / 動画未完了",
    "cases.case4.title": "Stock Bot 投資計画チュートリアル",
    "cases.case4.body": "投資計画チュートリアルの入口を構築し、ユーザーが繁体字中国語版から投資計画の流れ、操作手順、プラットフォーム機能を理解できるようにしました。ページは公開済みですが、チュートリアル動画は未完了で、今後は動画台本、録画、埋め込みが必要です。",
    "cases.case4.scopeLabel": "範囲",
    "cases.case4.scope": "投資計画チュートリアルページ、繁体字中国語入口、Render デプロイ確認、動画未完了",
    "cases.case4.linkLabel": "URL",
    "cases.case4.resultLabel": "成果",
    "cases.case4.result": "公開表示できる4つ目の事例を形成。動画完了後に完全なチュートリアル事例へ更新。",
    "cases.case5.status": "公開済み",
    "cases.case5.title": "Japan FB Tracker ペット関連企業トラッカー",
    "cases.case5.body": "日本の展示会と企業情報を追跡する入口を構築し、ペット関連企業、展示会リード、今後の営業開発リストを整理できるようにしました。OOG の産業データ収集と商務開発力を示す公開事例です。",
    "cases.case5.scopeLabel": "範囲",
    "cases.case5.scope": "ペット関連企業追跡、展示会リード、公開データ入口",
    "cases.case5.linkLabel": "URL",
    "cases.case5.resultLabel": "成果",
    "cases.case5.result": "公開表示できる5つ目の完了事例を形成。",
    "cases.case6.status": "公開済み",
    "cases.case6.title": "Asia Pet Export Hub ペット輸出プラットフォーム",
    "cases.case6.body": "アジアのペット商品輸出と企業情報のプラットフォームを構築し、OOG の越境商品、ペット産業、輸出入貿易の方向性を示す公開事例を補強しました。",
    "cases.case6.scopeLabel": "範囲",
    "cases.case6.scope": "ペット商品輸出、アジア企業情報、越境商務入口",
    "cases.case6.linkLabel": "URL",
    "cases.case6.resultLabel": "成果",
    "cases.case6.result": "公開表示できる6つ目の完了事例を形成。",
    "cases.case7.status": "公開済み",
    "cases.case7.title": "Japan Seafood Hub 水産企業プラットフォーム",
    "cases.case7.body": "日本の水産企業と商務情報の入口を構築しました。OOG の水産産業、サプライヤー整理、輸出入貿易の方向性を示す公開事例です。",
    "cases.case7.scopeLabel": "範囲",
    "cases.case7.scope": "水産企業情報、サプライヤー整理、越境商務入口",
    "cases.case7.linkLabel": "URL",
    "cases.case7.resultLabel": "成果",
    "cases.case7.result": "公開表示できる7つ目の完了事例を形成。",
    "lines.eyebrow": "4つの事業線",
    "lines.title": "7つの事例を、対外的に説明しやすい4つの事業線へ整理します。",
    "lines.body": "OOG は単なる制作実績の一覧ではなく、運営可能な商務ポートフォリオへ移行しています。展示プラットフォームは公開表示とイベント入口、投資教育は学習型プロダクト、ペット輸出と水産貿易は輸出入貿易とサプライヤー整理に対応します。",
    "lines.exhibit.title": "展示プラットフォーム",
    "lines.exhibit.body": "OOG 公式入口、Exhibit Platform、Intex Osaka Exhibitions を展示プラットフォーム線に整理します。主軸は多言語サイト、イベント展示、企業入口、公開デプロイです。",
    "lines.invest.title": "投資教育",
    "lines.invest.body": "Stock Bot 投資計画チュートリアルを投資教育線に整理します。金融知識、学習入口、操作チュートリアルとして位置づけ、投資助言業や金融商品取引業には踏み込みません。",
    "lines.pet.title": "ペット輸出",
    "lines.pet.body": "Japan FB Tracker と Asia Pet Export Hub をペット輸出線に整理します。ペット関連企業、展示会リード、アジアのサプライヤー、越境商務開発に使います。",
    "lines.seafood.title": "水産貿易",
    "lines.seafood.body": "Japan Seafood Hub を水産貿易線に整理します。水産サプライヤー整理、商務情報入口、将来の輸出入協業開発の基盤にします。",
    "systems.eyebrow": "内部システム",
    "systems.title": "構想から、デプロイ可能な会社インフラへ。",
    "systems.site": "株主、パートナー、社内メンバーのための公開ゲートウェイ。",
    "systems.deploy": "GitHub、Render、静的リサーチページ向けの再利用可能なデプロイ手順。",
    "systems.research": "プラットフォームの定位と戦略判断に使う競争情報ダッシュボード。",
    "diary.eyebrow": "構築日記",
    "diary.title": "意思決定、デプロイ、定位の修正を一つずつ記録します。",
    "diary.intro": "OOG の日記はマーケティング記事ではなく、会社をゼロから作るための作業記録です。名称、ウェブサイト、デプロイ、多言語対応、事業定位、次の戦略をここに整理していきます。",
    "diary.entry1.month": "2026 / 06",
    "diary.entry1.title": "OOG ゲートウェイサイトの第一段階を公開しました。",
    "diary.entry1.body": "本日、OOG を OPC Osaka Gateway の公開入口として確認し、GitHub と Render でのデプロイを完了しました。サイトは繁体字中国語、日本語、簡体字中国語に対応し、株主、パートナー、将来の大阪法人に関わるメンバーが確認しやすい形になっています。この段階の中心は、会社を大きく見せることではなく、信頼でき、継続的に更新でき、次の事業情報を受け止められる整った入口を作ることです。",
    "diary.entry1.point1": "OOG の名称と公開 URL を確定。",
    "diary.entry1.point2": "GitHub から Render へのデプロイ手順を構築。",
    "diary.entry1.point3": "大阪発ブティック OPC 企業、複数事業、AI 運営層の初期定位を整理。",
    "diary.entry2.month": "2026 / 06",
    "diary.entry2.title": "日本での登記事業目的と輸出入貿易の方向性を補強しました。",
    "diary.entry2.body": "本日、OOG サイトに日本法人登記で使える事業目的の文言が入っていることを確認し、輸出入貿易を商務システムと登記セクションに反映しました。これにより、大阪法人は AI、ウェブサイト、データ分析、展示プラットフォーム、教育コンテンツに加え、越境商品、デジタル製品、教材、ブランド代理にも展開余地を持てます。",
    "diary.entry2.point1": "完了：輸出入貿易と日本語の登記文言が公開サイトに表示されていることを確認。",
    "diary.entry2.point2": "未完了：Stock Bot チュートリアル動画は台本、録画、埋め込みが必要。",
    "diary.entry2.point3": "次の一手：登記事業目的の正式文言を司法書士または行政書士に確認します。",
    "diary.entry3.month": "2026 / 06",
    "diary.entry3.title": "完了事例を7件に拡充し、大型セクションのタイポグラフィを調整しました。",
    "diary.entry3.body": "本日、OOG に Japan FB Tracker、Asia Pet Export Hub、Japan Seafood Hub の3つの公開事例が追加されていることを確認しました。事例セクションは4件から7件へ拡張され、ペット関連企業、ペット輸出、水産企業という3つの越境商務ラインを補強しました。同時に、大見出し、事例カード、システムセクション、日記本文の文字サイズと行間を調整し、公開サイトの長文表示をより安定した印象に整えました。",
    "diary.entry3.point1": "完了：3つの産業事例を追加し、正式サイトでリンク表示を確認。",
    "diary.entry3.point2": "未完了：Stock Bot チュートリアル動画は未完成。Japan FB Tracker の実ページタイトルも後続で修正が必要。",
    "diary.entry3.point3": "次の一手：越境ペット、水産、輸出入貿易の事例整理を続け、OOG の商務方向を明確化します。",
    "diary.entry4.month": "2026 / 06",
    "diary.entry4.title": "公開サイトを巡回確認し、7つの事例とタイポグラフィ版が安定していることを確認しました。",
    "diary.entry4.body": "本日は OOG の定期メンテナンス確認を行い、GitHub gh-pages ブランチと Render の公開サイトが最新状態で維持されていることを確認しました。サイトには現在、7つの完了事例、CDP 競合データベース、日本での登記事業目的、輸出入貿易の方向性、調整済みの大型セクション向けタイポグラフィが反映されています。大きな新機能追加はないため、株主とパートナーが安定した版を確認できる状態を記録しました。",
    "diary.entry4.point1": "完了：OOG の事例、日記、文字スタイル、デプロイ元が正常であることを確認。",
    "diary.entry4.point2": "未完了：Stock Bot 動画、Japan FB Tracker 実ページタイトル、登記事業目的の正式確認は継続課題。",
    "diary.entry4.point3": "次の一手：越境ペット、水産、輸出入貿易の事例をより明確な商務ロードマップに整理します。",
    "diary.entry5.month": "2026 / 06",
    "diary.entry5.title": "月末メンテナンス確認を行い、OOG の次の商務ルートを整理しました。",
    "diary.entry5.body": "本日、OOG の月末メンテナンス確認を行い、公開サイトが7つの事例、CDP 競合データベース、日本での登記事業目的、輸出入貿易の方向性、テック感のあるタイポグラフィ版を維持していることを確認しました。直近で大きな新機能追加はないため、本日は状態整理を中心にしました。サイトは株主向けに見せられる基礎内容を備えており、次は越境ペット、水産、輸出入貿易の事例を実行可能な商務ロードマップへ整理する必要があります。",
    "diary.entry5.point1": "完了：公開サイトの内容、デプロイ元、主要セクションが安定していることを確認。",
    "diary.entry5.point2": "未完了：Stock Bot 動画、Japan FB Tracker ページタイトル、登記事業目的の正式確認は未完了。",
    "diary.entry5.point3": "次の一手：7つの事例を展示プラットフォーム、投資教育、ペット輸出、水産貿易の4つの事業ラインに整理します。",
    "diary.entry6.month": "2026 / 06",
    "diary.entry6.title": "4つの事業線を公開し、7つの事例を戦略的に分類しました。",
    "diary.entry6.body": "本日、OOG の公開サイトに「4つの事業線」セクションが追加されていることを確認しました。7つの事例を展示プラットフォーム、投資教育、ペット輸出、水産貿易へ整理し、サイトは単なる実績表示から事業構造の説明へ進みました。株主とパートナーは、OOG の商務方向、納品能力、今後拡張できる運営ラインをより早く理解できます。",
    "diary.entry6.point1": "完了：4つの事業線セクションをデプロイし、繁体字中国語、日本語、簡体字中国語、英語を同期。",
    "diary.entry6.point2": "未完了：Stock Bot 動画、Japan FB Tracker ページタイトル、登記事業目的の正式確認は継続課題。",
    "diary.entry6.point3": "次の一手：4つの事業線に収益モデル、対象顧客、優先開発順を追加します。",
    "diary.entry13.month": "2026 / 09",
    "diary.entry13.title": "クラウド事例の追跡を継続し、OOG 本体と5つの公開サービスが正常に稼働しています。",
    "diary.entry13.body": "本日は OOG の定例メンテナンスを行い、トップページの 3D Gateway、4つの事業線、7つの事例情報、競合データベース、4言語コンテンツに異常がないことを確認しました。OOG 本体と5つの公開事例は正常に応答しましたが、Intex Osaka Exhibitions と Japan FB Tracker は連続点検でもタイムアウトしており、復旧待ちサービスとして追跡します。他のサービスへの影響はありません。",
    "diary.entry13.point1": "完了：GitHub gh-pages、Render 公開サイト、トップページ、事例、競合情報を確認しました。",
    "diary.entry13.point2": "未完了：タイムアウトした2事例の追跡、Stock Bot 教学動画、Japan FB Tracker のタイトル、日本での登記事業目的の正式確認が残っています。",
    "diary.entry13.point3": "次のステップ：4つの事業線を9月の実行リストに変換し、料金プランと最初の対象顧客を定義します。",
    "diary.entry12.month": "2026 / 09",
    "diary.entry12.title": "日次クラウド点検を完了し、主要入口と5つの事例が正常に応答しました。",
    "diary.entry12.body": "本日は OOG 公開サイト、トップページの 3D Gateway、4つの事業線、7つの事例情報、CDP 競合データベースが維持されていることを確認しました。直近24時間に大きな機能追加はありません。OOG と5つの事例URLは正常に応答しましたが、Intex Osaka Exhibitions と Japan FB Tracker は今回の15秒点検でタイムアウトしたため、継続監視とします。OOG 本体の利用には影響ありません。",
    "diary.entry12.point1": "完了：公開サイト、4言語データ、事例、競合情報、GitHub から Render へのデプロイ状態を確認しました。",
    "diary.entry12.point2": "未完了：タイムアウトした2事例の継続確認、Stock Bot 教学動画、Japan FB Tracker のタイトル、日本での登記事業目的の正式確認が残っています。",
    "diary.entry12.point3": "次のステップ：4つの事業線の9月実行順を整理し、有料化できるサービスと対象顧客を優先して明確にします。",
    "diary.entry11.month": "2026 / 09",
    "diary.entry11.title": "9月最初のメンテナンスを完了し、OOG のクラウド入口と事業内容が安定していることを確認しました。",
    "diary.entry11.body": "本日は OOG の直近24時間のバージョン、画面、デプロイ状況を確認し、大きな新機能が追加されていないことを確認しました。トップページの 3D Gateway、4つの事業線、7つの完了事例、CDP 競合データベース、4言語の内容はすべて維持され、GitHub gh-pages と Render 公開サイトの配信フローも正常です。",
    "diary.entry11.point1": "完了：トップページ、事例リンク、競合内容、多言語データ、クラウド配信元を点検しました。",
    "diary.entry11.point2": "未完了：Stock Bot 教学動画、Japan FB Tracker のページタイトル、日本での登記事業目的の正式確認が残っています。",
    "diary.entry11.point3": "次のステップ：4つの事業線について、対外説明できる顧客層、収益モデル、9月の実行優先順位を定義します。",
    "diary.entry10.month": "2026 / 08",
    "diary.entry10.title": "定期クラウド点検を完了し、トップページの3Dアニメーションと主要コンテンツの安定を確認しました。",
    "diary.entry10.body": "本日は OOG の直近24時間のサイトおよびデプロイ状況を確認し、新たな大きな機能変更がないことを確認しました。GitHub の gh-pages ブランチ、Render 公開サイト、トップページの 3D Gateway アニメーション、4つの事業線、7つの完了事例、CDP 競合データベースはいずれも正常で、4言語の内容も一致しています。",
    "diary.entry10.point1": "完了：GitHub、Render、トップページの3Dアニメーション、事例セクション、競合データベースの表示を確認しました。",
    "diary.entry10.point2": "未完了：Stock Bot 教学動画、Japan FB Tracker のページタイトル、日本での登記事業目的の正式確認が残っています。",
    "diary.entry10.point3": "次のステップ：4つの事業線について、対象顧客、収益モデル、開発優先順位を明確にします。",
    "diary.entry9.month": "2026 / 07",
    "diary.entry9.title": "4つの事業線と7つの事例を継続維持し、公開サイトの安定を確認しました。",
    "diary.entry9.body": "本日、OOG の公開サイトが引き続き4つの事業線、7つの完了事例、CDP 競合データベース、多言語版の内容を維持していることを確認しました。大きな新機能は追加していないため、本日は定例メンテナンスとして記録し、株主とパートナーが同じ安定した版を見られる状態にしています。",
    "diary.entry9.point1": "完了：トップページ、事業線、事例、日記セクションの表示を確認。",
    "diary.entry9.point2": "未完了：Stock Bot 動画、Japan FB Tracker のページタイトル、登記事業目的の正式審査は未完了。",
    "diary.entry9.point3": "次の一手：各事業線の収益モデル、顧客像、対外説明の優先順位を整えます。",
    "diary.entry8.month": "2026 / 07",
    "diary.entry8.title": "4つの事業線公開後、最初の安定メンテナンス記録です。",
    "diary.entry8.body": "本日、OOG の公開サイトが引き続き4つの事業線、7つの完了事例、CDP 競合データベース、多言語版の内容を維持していることを確認しました。大きな新機能は追加していないため、今回の記録は、完成した事業線を継続追跡できる安定版として残すことが中心です。株主とパートナーには、同じ安定した版を見せられる状態です。",
    "diary.entry8.point1": "完了：4つの事業線、事例セクション、日記セクションの表示を正式サイトで確認。",
    "diary.entry8.point2": "未完了：Stock Bot 動画、Japan FB Tracker のページタイトル、登記事業目的の正式審査は未完了。",
    "diary.entry8.point3": "次の一手：4つの事業線ごとに、より明確な収益モデル、顧客像、優先順位を定義します。",
    "diary.entry7.month": "2026 / 07",
    "diary.entry7.title": "月初の安定メンテナンスで、4つの事業線と7つの事例が完全な状態で維持されていることを確認しました。",
    "diary.entry7.body": "本日、OOG の月初メンテナンス確認を行い、公開サイトが4つの事業線、7つの完了事例、CDP 競合データベース、日本での登記事業目的、輸出入貿易の方向性を維持していることを確認しました。最近は大きな機能追加がないため、本日は安定状態の記録を中心にしています。株主とパートナーに見せる基礎は揃っており、次は各事業線の収益モデルと顧客像を固める段階です。",
    "diary.entry7.point1": "完了：正式サイトの内容、ナビゲーション、事例、文字スタイルが正常であることを確認。",
    "diary.entry7.point2": "未完了：Stock Bot 動画、Japan FB Tracker のページタイトル、登記事業目的の正式審査は未完了。",
    "diary.entry7.point3": "次の一手：4つの事業線ごとに、より明確な収益モデル、顧客像、優先順位を定義します。",
    "contact.eyebrow": "次の一手",
    "contact.title": "ここを、対外的に明快で整った会社の玄関口にします。",
    "contact.body": "OPC Osaka Group の構造が具体化するにつれ、各事業、ダッシュボード、株主向けページ、社内ツールをここに集約できます。"
  },
  "zh-Hans": {
    "meta.description": "OPC Osaka Gateway 是大阪精品 OPC 公司与多产业事业的入口网站。",
    "nav.group": "集团",
    "nav.ventures": "事业",
    "nav.registration": "登记",
    "nav.competitors": "竞品",
    "nav.cases": "案例",
    "nav.lines": "路线",
    "nav.systems": "系统",
    "nav.diary": "日记",
    "nav.contact": "下一步",
    "hero.eyebrow": "大阪精品 OPC 事业入口",
    "hero.lead": "为 OPC Osaka Group 建立清晰、具精品感的入口：连接多产业事业、AI 运营、市场研究与部署系统。",
    "hero.primary": "查看事业方向",
    "hero.secondary": "查看内部系统",
    "signal.baseLabel": "据点",
    "signal.base": "日本大阪",
    "signal.roleLabel": "角色",
    "signal.role": "集团入口",
    "signal.focusLabel": "重点",
    "signal.focus": "AI 原生运营",
    "group.eyebrow": "集团定位",
    "group.title": "以大阪为基地，建立跨产业的精品运营集团。",
    "group.body": "OOG 是未来大阪公司架构的公开入口：以一个母品牌承接多个产业项目，并共享策略、研究、自动化与数字部署的运营层。",
    "ventures.ai.title": "AI 运营",
    "ventures.ai.body": "代理人治理、信号到行动流程，以及内部自动化模板。",
    "ventures.market.title": "市场情报",
    "ventures.market.body": "针对 CDP、客户互动与意图数据市场建立竞品研究仪表板。",
    "ventures.education.title": "教育与人才",
    "ventures.education.body": "学校平台、招聘流程、学生入口，以及跨境人才系统。",
    "ventures.commerce.title": "商务系统",
    "ventures.commerce.body": "库存、加盟、餐饮服务、进出口贸易，以及真实企业使用的轻量运营工具。",
    "registration.eyebrow": "日本登记事业项目",
    "registration.title": "将进出口贸易纳入大阪公司的事业目的。",
    "registration.body": "OOG 的事业范围除了 AI、网站、数据分析、展示平台与教育内容，也保留未来做跨境商品、设备、数字产品与品牌代理的弹性。日本公司登记时，可用较宽但清楚的日文事业目的描述。",
    "registration.trade.label": "登记建议",
    "registration.trade.jp": "各種商品の輸出入、販売、卸売、小売及び代理店業務",
    "registration.trade.note": "对应简中：各类商品之进出口、销售、批发、零售及代理业务。",
    "registration.digital.label": "延伸方向",
    "registration.digital.jp": "デジタルコンテンツ、ソフトウェア、教育教材及び関連商品の企画、制作、販売、輸出入及びライセンス業務",
    "registration.digital.note": "让网站、软件、教材、展示内容与跨境销售能放在同一个公司目的下。",
    "cases.eyebrow": "已完成案例",
    "cases.title": "第一个完成案例：OOG 多语言入口网站。",
    "cases.intro": "这个案例证明 OOG 不只是概念，而是已经能完成从命名、内容整理、GitHub 版本管理到 Render 公开部署的完整流程。",
    "cases.case1.status": "已完成",
    "cases.case1.title": "OPC Osaka Gateway 官方入口",
    "cases.case1.body": "建立一个可供股东、合作伙伴与内部成员查看的公开网站，支持繁体中文、日文、简体中文与英文，并通过 GitHub 与 Render 建立可持续更新的部署流程。",
    "cases.case1.scopeLabel": "范围",
    "cases.case1.scope": "品牌入口、四语内容、公司日记、公开部署",
    "cases.case1.stackLabel": "工具",
    "cases.case1.resultLabel": "成果",
    "cases.case1.result": "形成可展示、可追踪、可持续扩充的公司入口。",
    "cases.case2.status": "已确认四语上线",
    "cases.case2.title": "Exhibit Platform 展示平台",
    "cases.case2.body": "完成一个已上线的展示平台，并确认繁体中文、日文、简体中文与英文四语版本可公开浏览。此案例可作为 OOG 对外展示多语言网站部署与运营能力的完成作品。",
    "cases.case2.scopeLabel": "范围",
    "cases.case2.scope": "展示平台、四语上线、公开网址验证",
    "cases.case2.linkLabel": "网址",
    "cases.case2.resultLabel": "成果",
    "cases.case2.result": "形成第二个可公开展示的完成案例。",
    "cases.case3.status": "已上线",
    "cases.case3.title": "Intex Osaka Exhibitions 展览平台",
    "cases.case3.body": "建立以大阪展览活动为主题的公开展示平台，并完成 Render 线上部署。此案例补足 OOG 在活动信息、展览导览与地区型内容网站上的交付能力。",
    "cases.case3.scopeLabel": "范围",
    "cases.case3.scope": "大阪展览信息、公开展示页、Render 部署验证",
    "cases.case3.linkLabel": "网址",
    "cases.case3.resultLabel": "成果",
    "cases.case3.result": "形成第三个可公开展示的完成案例。",
    "cases.case4.status": "教学页已上线 / 视频待补",
    "cases.case4.title": "Stock Bot 投资计划教学",
    "cases.case4.body": "建立投资计划教学入口，让使用者可从繁体中文版本开始理解投资计划流程、操作步骤与平台功能。目前页面已公开上线，但教学视频尚未完成，后续需要补上视频脚本、录制与嵌入。",
    "cases.case4.scopeLabel": "范围",
    "cases.case4.scope": "投资计划教学页、繁中入口、Render 部署验证、视频待补",
    "cases.case4.linkLabel": "网址",
    "cases.case4.resultLabel": "成果",
    "cases.case4.result": "形成第四个可公开展示的案例；视频完成后再升级为完整教学案例。",
    "cases.case5.status": "已上线",
    "cases.case5.title": "Japan FB Tracker 宠物厂商追踪",
    "cases.case5.body": "建立日本展览与厂商信息追踪入口，协助整理宠物相关厂商、展会线索与后续开发名单，作为 OOG 在产业数据搜集与商务开发上的公开案例。",
    "cases.case5.scopeLabel": "范围",
    "cases.case5.scope": "宠物厂商追踪、展会线索、公开数据入口",
    "cases.case5.linkLabel": "网址",
    "cases.case5.resultLabel": "成果",
    "cases.case5.result": "形成第五个可公开展示的完成案例。",
    "cases.case6.status": "已上线",
    "cases.case6.title": "Asia Pet Export Hub 宠物出口平台",
    "cases.case6.body": "建立亚洲宠物产品出口与厂商信息平台，补足 OOG 在跨境商品、宠物产业与进出口贸易方向上的可展示成果。",
    "cases.case6.scopeLabel": "范围",
    "cases.case6.scope": "宠物产品出口、亚洲厂商信息、跨境商务入口",
    "cases.case6.linkLabel": "网址",
    "cases.case6.resultLabel": "成果",
    "cases.case6.result": "形成第六个可公开展示的完成案例。",
    "cases.case7.status": "已上线",
    "cases.case7.title": "Japan Seafood Hub 水产厂商平台",
    "cases.case7.body": "建立日本水产厂商与商务信息入口，作为 OOG 在水产产业、供应商整理与进出口贸易方向上的公开展示案例。",
    "cases.case7.scopeLabel": "范围",
    "cases.case7.scope": "水产厂商信息、供应商整理、跨境商务入口",
    "cases.case7.linkLabel": "网址",
    "cases.case7.resultLabel": "成果",
    "cases.case7.result": "形成第七个可公开展示的完成案例。",
    "lines.eyebrow": "四条事业线",
    "lines.title": "把七个案例整理成四条可对外说明的事业线。",
    "lines.body": "OOG 目前不只是作品列表，而是逐步形成可运营的商务组合：展示平台负责对外呈现与活动入口；投资教育保留教学型产品线；宠物出口与水产贸易则对应进出口贸易与供应商整理。",
    "lines.exhibit.title": "展示平台",
    "lines.exhibit.body": "将 OOG 官方入口、Exhibit Platform 与 Intex Osaka Exhibitions 统一归入展示平台线，主轴是多语言网站、活动展示、企业入口与公开部署。",
    "lines.invest.title": "投资教育",
    "lines.invest.body": "将 Stock Bot 投资计划教学归入投资教育线，定位为金融知识、学习入口与操作教学，不碰投资顾问或金融商品交易业务。",
    "lines.pet.title": "宠物出口",
    "lines.pet.body": "将 Japan FB Tracker 与 Asia Pet Export Hub 归入宠物出口线，用于整理宠物厂商、展会线索、亚洲供应商与跨境商务开发。",
    "lines.seafood.title": "水产贸易",
    "lines.seafood.body": "将 Japan Seafood Hub 归入水产贸易线，作为水产供应商整理、商务信息入口与未来进出口合作开发的基础。",
    "systems.eyebrow": "内部系统",
    "systems.title": "从概念到可部署的公司基础设施。",
    "systems.site": "供股东、合作伙伴与内部成员使用的公开入口。",
    "systems.deploy": "可重复使用的 GitHub、Render 与静态研究页部署流程。",
    "systems.research": "用于平台定位与策略判断的竞争情报仪表板。",
    "diary.eyebrow": "建立日记",
    "diary.title": "把每一次决策、部署与定位修正留下记录。",
    "diary.intro": "OOG 的日记不是营销文章，而是公司从零开始建立时的工作记录：命名、网站、部署、多语言、事业定位与下一步策略，都会在这里逐步整理。",
    "diary.entry1.month": "2026 / 06",
    "diary.entry1.title": "OOG 入口网站完成第一阶段上线。",
    "diary.entry1.body": "今天确认 OOG 作为 OPC Osaka Gateway 的公开入口，并完成 GitHub 与 Render 部署。网站已支持繁体中文、日文与简体中文，方便股东、合作伙伴与未来大阪法人相关成员查看。这一阶段的核心不是把公司包装得很大，而是先建立一个可信、可持续更新、能承接后续事业信息的干净入口。",
    "diary.entry1.point1": "完成 OOG 命名与公开网址。",
    "diary.entry1.point2": "建立 GitHub 到 Render 的部署流程。",
    "diary.entry1.point3": "确立大阪精品 OPC 公司、多产业事业与 AI 运营层的初步定位。",
    "diary.entry2.month": "2026 / 06",
    "diary.entry2.title": "补强日本登记事业目的与进出口贸易方向。",
    "diary.entry2.body": "今日确认 OOG 网站已纳入日本公司登记可用的事业目的文字，并将进出口贸易补进商务系统与登记区块。这让大阪法人未来除了 AI、网站、数据分析、展示平台与教育内容，也能保留跨境商品、数字产品、教材与品牌代理的运营弹性。",
    "diary.entry2.point1": "完成：确认进出口贸易与日文登记文字已出现在公开网站。",
    "diary.entry2.point2": "待补：Stock Bot 教学视频仍需脚本、录制与嵌入。",
    "diary.entry2.point3": "下一步：将登记事业目的交由日本司法书士或行政书士确认正式送件文字。",
    "diary.entry3.month": "2026 / 06",
    "diary.entry3.title": "成功案例扩充到七个，并完成大区块字体优化。",
    "diary.entry3.body": "今日确认 OOG 已新增三个公开案例：Japan FB Tracker、Asia Pet Export Hub 与 Japan Seafood Hub。案例区块从原本四个扩充到七个，补强宠物厂商、宠物出口与水产厂商三条跨境商务线。同时完成大标题、案例卡、系统区块与日记内容的字体比例调整，让公开网站在大面积阅读时更稳定、正式。",
    "diary.entry3.point1": "完成：新增三个产业案例并确认正式站已显示链接。",
    "diary.entry3.point2": "待补：Stock Bot 教学视频仍需完成，Japan FB Tracker 的实际页面标题也需后续校正。",
    "diary.entry3.point3": "下一步：持续整理跨境宠物、水产与进出口贸易案例，让 OOG 的商务方向更清楚。",
    "diary.entry4.month": "2026 / 06",
    "diary.entry4.title": "完成公开站巡检，确认七个案例与字体版本维持稳定。",
    "diary.entry4.body": "今日进行 OOG 例行维护检查，确认 GitHub gh-pages 分支与 Render 正式站仍维持最新版本。网站目前保留七个完成案例、CDP 竞品数据库、日本登记事业目的、进出口贸易方向与优化后的大区块字体样式。今日没有新增大型功能，因此以维护记录为主，确保股东与合作伙伴看到的是稳定版本。",
    "diary.entry4.point1": "完成：检查 OOG 案例区、日记区、字体样式与部署来源仍正常。",
    "diary.entry4.point2": "待补：Stock Bot 教学视频、Japan FB Tracker 实际页面标题、登记事业目的正式审核仍需后续处理。",
    "diary.entry4.point3": "下一步：把跨境宠物、水产与进出口贸易案例整理成更清楚的商务路线图。",
    "diary.entry5.month": "2026 / 06",
    "diary.entry5.title": "月末维护巡检，整理 OOG 下一步商务路线。",
    "diary.entry5.body": "今日进行 OOG 月末维护检查，确认公开站仍维持七个案例、CDP 竞品数据库、日本登记事业目的、进出口贸易方向与科技感字体版本。最近没有新增大型功能，因此本日重点放在状态整理：网站已具备对股东展示的基础内容，下一步需要把跨境宠物、水产与进出口贸易案例整理成可执行的商务路线图。",
    "diary.entry5.point1": "完成：确认正式站内容、部署来源与核心区块维持稳定。",
    "diary.entry5.point2": "待补：Stock Bot 教学视频、Japan FB Tracker 页面标题、登记事业目的正式审核仍未完成。",
    "diary.entry5.point3": "下一步：把七个案例分成展示平台、投资教育、宠物出口与水产贸易四条可对外说明的事业线。",
    "diary.entry6.month": "2026 / 06",
    "diary.entry6.title": "四条事业线正式上线，七个案例完成策略归类。",
    "diary.entry6.body": "今日确认 OOG 正式站已新增「四条事业线」区块，将七个案例整理为展示平台、投资教育、宠物出口与水产贸易。这让网站从案例展示进一步变成事业架构说明，股东与合作伙伴可以更快理解 OOG 的商务方向、交付能力与未来可扩充的运营线。",
    "diary.entry6.point1": "完成：四条事业线区块已部署，并同步繁中、日文、简中、英文内容。",
    "diary.entry6.point2": "待补：Stock Bot 教学视频、Japan FB Tracker 页面标题、登记事业目的正式审核仍需处理。",
    "diary.entry6.point3": "下一步：为四条事业线补上更具体的收益模式、目标客群与优先开发顺序。",
    "diary.entry13.month": "2026 / 09",
    "diary.entry13.title": "持续追踪云端案例，OOG 主站与五个公开服务保持正常。",
    "diary.entry13.body": "今日完成 OOG 例行维护，确认首页 3D Gateway、四条事业线、七个案例资料、竞品数据库及四语内容没有异常。主站与五个公开案例正常响应；Intex Osaka Exhibitions 与 Japan FB Tracker 连续巡检仍超时，目前列为待恢复服务，OOG 主站及其他案例不受影响。",
    "diary.entry13.point1": "完成：检查 GitHub gh-pages、Render 正式站、首页界面、案例与竞品资料。",
    "diary.entry13.point2": "待补：追踪两个超时案例，完成 Stock Bot 教学影片、Japan FB Tracker 标题与日本登记事业目的审核。",
    "diary.entry13.point3": "下一步：把四条事业线转成九月可执行清单，先定义收费方案与首批目标客户。",
    "diary.entry12.month": "2026 / 09",
    "diary.entry12.title": "完成每日云端巡检，核心入口与五个案例响应正常。",
    "diary.entry12.body": "今日确认 OOG 正式站、首页 3D Gateway、四条事业线、七个案例资料与 CDP 竞品数据库维持完整，最近24小时没有新增重大功能。OOG 与五个案例网址成功响应；Intex Osaka Exhibitions 与 Japan FB Tracker 在本次15秒巡检中超时，先列入持续观察，不影响 OOG 主站使用。",
    "diary.entry12.point1": "完成：验证主站、四语数据、案例区、竞品区与 GitHub 至 Render 的部署状态。",
    "diary.entry12.point2": "待补：持续检查两个超时案例，并完成 Stock Bot 教学影片、Japan FB Tracker 标题与日本登记事业目的正式审核。",
    "diary.entry12.point3": "下一步：整理四条事业线的九月执行顺序，优先补上可收费服务与目标客户。",
    "diary.entry11.month": "2026 / 09",
    "diary.entry11.title": "完成九月首轮维护，确认 OOG 云端入口与事业内容持续稳定。",
    "diary.entry11.body": "今日检查 OOG 最近24小时的版本、界面与部署状态，期间没有新增重大功能。首页 3D Gateway、四条事业线、七个完成案例、CDP 竞品数据库与四语内容均维持完整，GitHub gh-pages 与 Render 正式站的发布流程也保持正常。",
    "diary.entry11.point1": "完成：巡检首页界面、案例链接、竞品内容、多语数据与云端部署来源。",
    "diary.entry11.point2": "待补：Stock Bot 教学影片、Japan FB Tracker 页面标题及日本登记事业目的正式审核仍待完成。",
    "diary.entry11.point3": "下一步：为四条事业线建立可对外说明的客群、收入模式与九月执行优先序。",
    "diary.entry10.month": "2026 / 08",
    "diary.entry10.title": "完成例行云端巡检，确认首页 3D 动画与核心内容维持稳定。",
    "diary.entry10.body": "今日检查 OOG 最近24小时的网站与部署状态，未发现新的重大功能变动。GitHub gh-pages 分支、Render 正式站、首页 3D Gateway 动画、四条事业线、七个完成案例与 CDP 竞品数据库均维持正常，四语内容也保持一致，供股东与合作伙伴持续查阅。",
    "diary.entry10.point1": "完成：确认 GitHub、Render、首页 3D 动画、案例区与竞品数据库均可正常显示。",
    "diary.entry10.point2": "待补：Stock Bot 教学影片、Japan FB Tracker 页面标题及日本登记事业目的正式审核仍待完成。",
    "diary.entry10.point3": "下一步：补强四条事业线的目标客户、收入模式与优先开发顺序。",
    "diary.entry9.month": "2026 / 07",
    "diary.entry9.title": "持续维护四条事业线与七个案例，确认正式站状态稳定。",
    "diary.entry9.body": "今日确认 OOG 公开站内容仍维持四条事业线、七个完成案例、CDP 竞品数据库与多语版本一致，没有新增大型功能。这篇日记主要是做例行维护纪录，让股东与合作伙伴看到的正式版本保持一致、清楚且可追踪。",
    "diary.entry9.point1": "完成：检查首页、四条事业线、案例区与日记区的显示状态。",
    "diary.entry9.point2": "待补：Stock Bot 教学视频、Japan FB Tracker 页面标题、登记事业目的正式审核仍待完成。",
    "diary.entry9.point3": "下一步：补强各事业线的收益模式、客群定位与对外说明顺序。",
    "diary.entry8.month": "2026 / 07",
    "diary.entry8.title": "完成四条事业线后，进行第一轮稳定维护纪录。",
    "diary.entry8.body": "今日确认 OOG 的公开站仍维持四条事业线、七个完成案例、CDP 竞品数据库与多语版本内容一致。今天没有新增大型功能，重点是把刚完成的事业线整理成可持续追踪的状态，让股东与合作伙伴看到的是同一个稳定版本。",
    "diary.entry8.point1": "完成：检查四条事业线、案例区与日记区在正式站上显示正常。",
    "diary.entry8.point2": "待补：Stock Bot 教学视频、Japan FB Tracker 页面标题、登记事业目的正式审核仍待完成。",
    "diary.entry8.point3": "下一步：为四条事业线补上更清楚的收益模式、目标客群与优先顺序。",
    "diary.entry7.month": "2026 / 07",
    "diary.entry7.title": "月初稳定维护，确认四条事业线与七个案例维持完整。",
    "diary.entry7.body": "今日进行 OOG 月初维护巡检，确认公开站仍维持四条事业线、七个完成案例、CDP 竞品数据库、日本登记事业目的与进出口贸易方向。近期没有新增大型功能，因此本日以稳定状态纪录为主，确保股东与合作伙伴看到的是同一个清楚版本。",
    "diary.entry7.point1": "完成：确认正式站内容、导览、案例与字体样式都维持正常。",
    "diary.entry7.point2": "待补：Stock Bot 教学视频、Japan FB Tracker 页面标题、登记事业目的正式审核仍未完成。",
    "diary.entry7.point3": "下一步：为四条事业线补上更明确的收益模式、目标客群与优先顺序。",
    "contact.eyebrow": "下一步",
    "contact.title": "把这里作为对外清楚、干净的公司入口。",
    "contact.body": "随着 OPC Osaka Group 的架构逐步具体化，可将各事业、仪表板、股东页面与内部工具集中放在这里。"
  },
  en: {
    "meta.description": "OPC Osaka Gateway is the entry site for a boutique Osaka OPC company and multi-industry ventures.",
    "nav.group": "Group",
    "nav.ventures": "Ventures",
    "nav.registration": "Registry",
    "nav.competitors": "Competitors",
    "nav.cases": "Cases",
    "nav.lines": "Lines",
    "nav.systems": "Systems",
    "nav.diary": "Diary",
    "nav.contact": "Next",
    "hero.eyebrow": "Osaka boutique OPC venture gateway",
    "hero.lead": "A clear, refined entry point for OPC Osaka Group: connecting multi-industry ventures, AI operations, market research, and deployment systems.",
    "hero.primary": "Explore ventures",
    "hero.secondary": "View systems",
    "signal.baseLabel": "Base",
    "signal.base": "Osaka, Japan",
    "signal.roleLabel": "Role",
    "signal.role": "Group gateway",
    "signal.focusLabel": "Focus",
    "signal.focus": "AI-native operations",
    "group.eyebrow": "Group positioning",
    "group.title": "A boutique operating group built in Osaka for multiple industries.",
    "group.body": "OOG is the public doorway for a future Osaka company structure: one parent identity, multiple industry projects, and a shared operating layer for strategy, research, automation, and digital deployment.",
    "ventures.ai.title": "AI Operations",
    "ventures.ai.body": "Agent governance, signal-to-action workflows, and internal automation templates.",
    "ventures.market.title": "Market Intelligence",
    "ventures.market.body": "Competitive research dashboards for CDP, customer engagement, and intent data markets.",
    "ventures.education.title": "Education & Talent",
    "ventures.education.body": "School platforms, hiring workflows, student portals, and cross-border talent systems.",
    "ventures.commerce.title": "Commerce Systems",
    "ventures.commerce.body": "Inventory, franchise, food-service, import/export trade, and lightweight operating tools for real businesses.",
    "registration.eyebrow": "Japan company registry purposes",
    "registration.title": "Include import/export trade in the Osaka company's business purposes.",
    "registration.body": "Alongside AI, websites, data analysis, exhibit platforms, and education content, OOG keeps room for cross-border goods, equipment, digital products, and brand agency work. For Japanese incorporation, this can be written as a broad but clear business purpose.",
    "registration.trade.label": "Suggested wording",
    "registration.trade.jp": "各種商品の輸出入、販売、卸売、小売及び代理店業務",
    "registration.trade.note": "Meaning: import/export, sales, wholesale, retail, and agency services for various goods.",
    "registration.digital.label": "Expansion area",
    "registration.digital.jp": "デジタルコンテンツ、ソフトウェア、教育教材及び関連商品の企画、制作、販売、輸出入及びライセンス業務",
    "registration.digital.note": "This keeps websites, software, learning materials, exhibit content, and cross-border sales under one company purpose.",
    "cases.eyebrow": "Completed case",
    "cases.title": "First completed case: the OOG multilingual gateway site.",
    "cases.intro": "This case shows that OOG is not only a concept. It can already complete the full workflow from naming, content organization, GitHub version control, and public Render deployment.",
    "cases.case1.status": "Completed",
    "cases.case1.title": "OPC Osaka Gateway official entry site",
    "cases.case1.body": "A public website for shareholders, partners, and internal members, supporting Traditional Chinese, Japanese, Simplified Chinese, and English, with a sustainable GitHub-to-Render deployment flow.",
    "cases.case1.scopeLabel": "Scope",
    "cases.case1.scope": "Brand gateway, four-language content, company diary, public deployment",
    "cases.case1.stackLabel": "Stack",
    "cases.case1.resultLabel": "Result",
    "cases.case1.result": "A presentable, trackable, continuously expandable company gateway.",
    "cases.case2.status": "Four languages verified",
    "cases.case2.title": "Exhibit Platform",
    "cases.case2.body": "A live exhibit platform with Traditional Chinese, Japanese, Simplified Chinese, and English confirmed publicly available. This case demonstrates OOG's ability to deploy and operate multilingual websites as finished public work.",
    "cases.case2.scopeLabel": "Scope",
    "cases.case2.scope": "Exhibit platform, four-language launch, public URL verification",
    "cases.case2.linkLabel": "URL",
    "cases.case2.resultLabel": "Result",
    "cases.case2.result": "A second completed case that can be shared publicly.",
    "cases.case3.status": "Live",
    "cases.case3.title": "Intex Osaka Exhibitions platform",
    "cases.case3.body": "A public exhibit platform focused on Osaka exhibition activity, deployed live on Render. This case strengthens OOG's delivery record for event information, exhibition navigation, and local content websites.",
    "cases.case3.scopeLabel": "Scope",
    "cases.case3.scope": "Osaka exhibition information, public exhibit page, Render deployment verification",
    "cases.case3.linkLabel": "URL",
    "cases.case3.resultLabel": "Result",
    "cases.case3.result": "A third completed case that can be shared publicly.",
    "cases.case4.status": "Page live / video pending",
    "cases.case4.title": "Stock Bot investment plan tutorial",
    "cases.case4.body": "A tutorial entry point for investment plans, allowing users to start from the Traditional Chinese version and understand the plan flow, operating steps, and platform features. The page is live, but the tutorial video is not complete yet; the next work is script writing, recording, and embedding.",
    "cases.case4.scopeLabel": "Scope",
    "cases.case4.scope": "Investment plan tutorial page, Traditional Chinese entry, Render deployment verification, video pending",
    "cases.case4.linkLabel": "URL",
    "cases.case4.resultLabel": "Result",
    "cases.case4.result": "A fourth public case is available; it will become a complete tutorial case after the video is finished.",
    "cases.case5.status": "Live",
    "cases.case5.title": "Japan FB Tracker pet company tracker",
    "cases.case5.body": "A tracker for Japanese exhibition and company information, organizing pet-related companies, exhibition leads, and follow-up business development lists. This is a public case for OOG's industry data collection and commercial development work.",
    "cases.case5.scopeLabel": "Scope",
    "cases.case5.scope": "Pet company tracking, exhibition leads, public data entry point",
    "cases.case5.linkLabel": "URL",
    "cases.case5.resultLabel": "Result",
    "cases.case5.result": "A fifth completed case that can be shared publicly.",
    "cases.case6.status": "Live",
    "cases.case6.title": "Asia Pet Export Hub",
    "cases.case6.body": "A platform for Asian pet product export and company information, strengthening OOG's public portfolio for cross-border goods, the pet industry, and import/export trade.",
    "cases.case6.scopeLabel": "Scope",
    "cases.case6.scope": "Pet product export, Asian company information, cross-border commerce entry point",
    "cases.case6.linkLabel": "URL",
    "cases.case6.resultLabel": "Result",
    "cases.case6.result": "A sixth completed case that can be shared publicly.",
    "cases.case7.status": "Live",
    "cases.case7.title": "Japan Seafood Hub",
    "cases.case7.body": "A public entry point for Japanese seafood companies and commercial information, showing OOG's direction in the seafood industry, supplier organization, and import/export trade.",
    "cases.case7.scopeLabel": "Scope",
    "cases.case7.scope": "Seafood company information, supplier organization, cross-border commerce entry point",
    "cases.case7.linkLabel": "URL",
    "cases.case7.resultLabel": "Result",
    "cases.case7.result": "A seventh completed case that can be shared publicly.",
    "lines.eyebrow": "Four venture lines",
    "lines.title": "Organizing seven cases into four external-facing venture lines.",
    "lines.body": "OOG is no longer only a portfolio list. It is becoming an operating commerce portfolio: exhibit platforms handle public presentation and event entry points; investment education keeps the tutorial product line; pet export and seafood trade map to import/export trade and supplier organization.",
    "lines.exhibit.title": "Exhibit platforms",
    "lines.exhibit.body": "OPC Osaka Gateway, Exhibit Platform, and Intex Osaka Exhibitions are grouped into the exhibit-platform line, focused on multilingual websites, event presentation, company entry sites, and public deployment.",
    "lines.invest.title": "Investment education",
    "lines.invest.body": "The Stock Bot investment plan tutorial is grouped into the investment-education line, positioned as financial literacy, learning entry, and operating tutorials without entering investment advisory or financial instruments business.",
    "lines.pet.title": "Pet export",
    "lines.pet.body": "Japan FB Tracker and Asia Pet Export Hub are grouped into the pet-export line for organizing pet companies, exhibition leads, Asian suppliers, and cross-border business development.",
    "lines.seafood.title": "Seafood trade",
    "lines.seafood.body": "Japan Seafood Hub is grouped into the seafood-trade line as a base for seafood supplier organization, commercial information, and future import/export collaboration.",
    "systems.eyebrow": "Internal systems",
    "systems.title": "From concept to deployable company infrastructure.",
    "systems.site": "A public gateway for shareholders, partners, and internal navigation.",
    "systems.deploy": "A repeatable deployment flow for GitHub, Render, and static research pages.",
    "systems.research": "A competitive intelligence dashboard for platform positioning and strategy.",
    "diary.eyebrow": "Build diary",
    "diary.title": "Recording each decision, deployment, and positioning adjustment.",
    "diary.intro": "The OOG diary is not marketing copy. It is a working record of building the company from zero: naming, website, deployment, multilingual content, venture positioning, and next-step strategy will be organized here over time.",
    "diary.entry1.month": "2026 / 06",
    "diary.entry1.title": "The first stage of the OOG gateway site is live.",
    "diary.entry1.body": "Today we confirmed OOG as the public gateway for OPC Osaka Gateway and completed the GitHub and Render deployment. The site now supports Traditional Chinese, Japanese, Simplified Chinese, and English, making it easier for shareholders, partners, and future Osaka company members to review. The goal at this stage is not to make the company look oversized, but to establish a credible, clean, continuously updateable front door that can hold future venture information.",
    "diary.entry1.point1": "Confirmed the OOG name and public URL.",
    "diary.entry1.point2": "Built the GitHub-to-Render deployment flow.",
    "diary.entry1.point3": "Clarified the initial positioning for an Osaka boutique OPC company, multi-industry ventures, and an AI operations layer.",
    "diary.entry2.month": "2026 / 06",
    "diary.entry2.title": "Strengthened Japan registry purposes and import/export trade direction.",
    "diary.entry2.body": "Today we confirmed that the OOG site includes business-purpose wording suitable for Japanese incorporation and added import/export trade to the commerce systems and registry sections. This gives the future Osaka company room to operate beyond AI, websites, data analysis, exhibit platforms, and education content, while keeping flexibility for cross-border goods, digital products, learning materials, and brand agency work.",
    "diary.entry2.point1": "Done: confirmed import/export trade and Japanese registry wording on the public site.",
    "diary.entry2.point2": "Pending: the Stock Bot tutorial video still needs scripting, recording, and embedding.",
    "diary.entry2.point3": "Next: have a Japanese judicial scrivener or administrative scrivener review the official registry wording.",
    "diary.entry3.month": "2026 / 06",
    "diary.entry3.title": "Expanded completed cases to seven and refined large-section typography.",
    "diary.entry3.body": "Today we confirmed that OOG now includes three additional public cases: Japan FB Tracker, Asia Pet Export Hub, and Japan Seafood Hub. The case section expanded from four to seven entries, strengthening three cross-border commerce lines: pet companies, pet export, and seafood companies. We also refined typography across large titles, case cards, systems, and diary content so the public site reads more steadily and formally in larger sections.",
    "diary.entry3.point1": "Done: added three industry cases and verified their links on the public site.",
    "diary.entry3.point2": "Pending: the Stock Bot tutorial video is still incomplete, and the live Japan FB Tracker page title needs a follow-up correction.",
    "diary.entry3.point3": "Next: keep organizing cross-border pet, seafood, and import/export trade cases so OOG's commerce direction becomes clearer.",
    "diary.entry4.month": "2026 / 06",
    "diary.entry4.title": "Completed a public-site check and confirmed the seven-case typography version is stable.",
    "diary.entry4.body": "Today we performed a routine OOG maintenance check and confirmed that the GitHub gh-pages branch and Render public site remain on the latest version. The site currently holds seven completed cases, the CDP competitor database, Japan registry-purpose wording, import/export trade direction, and refined typography for large sections. No major feature was added today, so this entry records the stable version available to shareholders and partners.",
    "diary.entry4.point1": "Done: checked the OOG case section, diary section, typography, and deployment source.",
    "diary.entry4.point2": "Pending: Stock Bot tutorial video, Japan FB Tracker live page title, and final review of registry-purpose wording still need follow-up.",
    "diary.entry4.point3": "Next: organize the cross-border pet, seafood, and import/export trade cases into a clearer commerce roadmap.",
    "diary.entry5.month": "2026 / 06",
    "diary.entry5.title": "Completed a month-end maintenance check and organized OOG's next commerce route.",
    "diary.entry5.body": "Today we performed a month-end OOG maintenance check and confirmed that the public site still holds seven cases, the CDP competitor database, Japan registry-purpose wording, import/export trade direction, and the technology-oriented typography version. There were no major feature additions recently, so today's focus is status organization: the site now has a shareholder-ready content base, and the next step is to turn the cross-border pet, seafood, and import/export trade cases into an executable commerce roadmap.",
    "diary.entry5.point1": "Done: confirmed that public-site content, deployment source, and core sections remain stable.",
    "diary.entry5.point2": "Pending: Stock Bot tutorial video, Japan FB Tracker page title, and formal registry-purpose review remain incomplete.",
    "diary.entry5.point3": "Next: group the seven cases into four external-facing venture lines: exhibit platforms, investment education, pet export, and seafood trade.",
    "diary.entry6.month": "2026 / 06",
    "diary.entry6.title": "Four venture lines are live, and the seven cases are now strategically grouped.",
    "diary.entry6.body": "Today we confirmed that the OOG public site now includes the Four Venture Lines section, organizing seven cases into exhibit platforms, investment education, pet export, and seafood trade. This moves the site from a case showcase into a clearer business-structure explanation, helping shareholders and partners understand OOG's commerce direction, delivery capability, and expandable operating lines.",
    "diary.entry6.point1": "Done: deployed the four venture lines section and synchronized Traditional Chinese, Japanese, Simplified Chinese, and English content.",
    "diary.entry6.point2": "Pending: Stock Bot tutorial video, Japan FB Tracker page title, and formal registry-purpose review still need follow-up.",
    "diary.entry6.point3": "Next: add clearer revenue models, target customers, and development priorities for the four venture lines.",
    "diary.entry13.month": "2026 / 09",
    "diary.entry13.title": "Continued monitoring cloud cases; the OOG main site and five public services remain healthy.",
    "diary.entry13.body": "Today we completed routine OOG maintenance and confirmed that the homepage 3D Gateway, four venture lines, seven case records, competitor database, and four-language content remain intact. The main site and five public cases responded normally; Intex Osaka Exhibitions and Japan FB Tracker continued to time out in consecutive checks and are being tracked as services awaiting recovery. The OOG main site and other cases are unaffected.",
    "diary.entry13.point1": "Done: checked GitHub gh-pages, the Render production site, homepage interface, cases, and competitor data.",
    "diary.entry13.point2": "Pending: track the two timed-out cases and complete the Stock Bot tutorial video, Japan FB Tracker title, and formal review of Japan registry purposes.",
    "diary.entry13.point3": "Next: turn the four venture lines into a September execution list, starting with pricing packages and initial target customers.",
    "diary.entry12.month": "2026 / 09",
    "diary.entry12.title": "Completed the daily cloud check; the core gateway and five case sites responded normally.",
    "diary.entry12.body": "Today we confirmed that the OOG production site, homepage 3D Gateway, four venture lines, seven case records, and CDP competitor database remain intact, with no major feature additions in the last 24 hours. OOG and five case URLs responded successfully; Intex Osaka Exhibitions and Japan FB Tracker timed out during this 15-second check and will remain under observation. The OOG main site is unaffected.",
    "diary.entry12.point1": "Done: verified the main site, four-language data, case and competitor sections, and the GitHub-to-Render deployment status.",
    "diary.entry12.point2": "Pending: continue checking the two timed-out cases and complete the Stock Bot tutorial video, Japan FB Tracker title, and formal review of Japan registry purposes.",
    "diary.entry12.point3": "Next: organize September execution priorities for the four venture lines, starting with billable services and target customers.",
    "diary.entry11.month": "2026 / 09",
    "diary.entry11.title": "Completed the first September maintenance check and confirmed OOG's cloud gateway and venture content remain stable.",
    "diary.entry11.body": "Today we reviewed OOG's version, interface, and deployment status over the last 24 hours and found no major new feature additions. The homepage 3D Gateway, four venture lines, seven completed cases, CDP competitor database, and four-language content remain intact, while the GitHub gh-pages and Render production publishing flow continues to operate normally.",
    "diary.entry11.point1": "Done: checked the homepage interface, case links, competitor content, multilingual data, and cloud deployment source.",
    "diary.entry11.point2": "Pending: the Stock Bot tutorial video, Japan FB Tracker page title, and formal review of Japan registry purposes remain incomplete.",
    "diary.entry11.point3": "Next: define externally explainable customer segments, revenue models, and September execution priorities for the four venture lines.",
    "diary.entry10.month": "2026 / 08",
    "diary.entry10.title": "Completed a routine cloud check and confirmed the homepage 3D animation and core content remain stable.",
    "diary.entry10.body": "Today we reviewed OOG's website and deployment status over the last 24 hours and found no major new feature changes. The GitHub gh-pages branch, Render production site, homepage 3D Gateway animation, four venture lines, seven completed cases, and CDP competitor database are all operating normally, with content remaining consistent across four languages.",
    "diary.entry10.point1": "Done: verified GitHub, Render, the homepage 3D animation, case section, and competitor database display correctly.",
    "diary.entry10.point2": "Pending: the Stock Bot tutorial video, Japan FB Tracker page title, and formal review of Japan registry purposes remain incomplete.",
    "diary.entry10.point3": "Next: strengthen the target customers, revenue model, and development priorities for each of the four venture lines.",
    "diary.entry9.month": "2026 / 07",
    "diary.entry9.title": "We kept the four venture lines and seven cases stable and confirmed the public site is healthy.",
    "diary.entry9.body": "Today we confirmed that the OOG public site still keeps the four venture lines, seven completed cases, the CDP competitor database, and synchronized multilingual content. No major feature was added today, so this entry is a routine maintenance note that keeps the official version consistent, clear, and easy to track for shareholders and partners.",
    "diary.entry9.point1": "Done: checked the homepage, venture lines, case area, and diary section display.",
    "diary.entry9.point2": "Pending: the Stock Bot tutorial video, Japan FB Tracker page title, and formal registry-purpose review are still incomplete.",
    "diary.entry9.point3": "Next: strengthen the revenue model, audience positioning, and external explanation order for each line.",
    "diary.entry8.month": "2026 / 07",
    "diary.entry8.title": "A first stability note after launching the four venture lines.",
    "diary.entry8.body": "Today we confirmed that the OOG public site still keeps the four venture lines, seven completed cases, the CDP competitor database, and synchronized multilingual content. No major feature was added today; the focus was to keep the newly completed venture lines in a trackable stable state so shareholders and partners see the same version.",
    "diary.entry8.point1": "Done: verified the four venture lines, case section, and diary section display correctly on the live site.",
    "diary.entry8.point2": "Pending: the Stock Bot tutorial video, Japan FB Tracker page title, and formal registry-purpose review are still incomplete.",
    "diary.entry8.point3": "Next: define clearer revenue models, target customers, and priorities for each of the four venture lines.",
    "diary.entry7.month": "2026 / 07",
    "diary.entry7.title": "Month-start maintenance confirmed the four venture lines and seven cases are intact.",
    "diary.entry7.body": "Today we ran a month-start OOG maintenance check and confirmed that the public site still maintains four venture lines, seven completed cases, the CDP competitor database, Japan registry-purpose wording, and the import/export trade direction. No major feature additions were made recently, so today's entry is a stability record to ensure shareholders and partners are seeing the same clear version.",
    "diary.entry7.point1": "Done: verified that the public-site content, navigation, cases, and typography remain normal.",
    "diary.entry7.point2": "Pending: Stock Bot tutorial video, Japan FB Tracker page title, and formal registry-purpose review are still incomplete.",
    "diary.entry7.point3": "Next: define clearer revenue models, target customers, and priorities for the four venture lines.",
    "contact.eyebrow": "Next step",
    "contact.title": "Use this as the clear public front door for the company.",
    "contact.body": "As the OPC Osaka Group structure becomes more concrete, each venture, dashboard, shareholder page, and internal tool can be gathered here."
  }
};

function applyLanguage(lang) {
  const dictionary = translations[lang] || translations["zh-Hant"];

  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const value = dictionary[node.dataset.i18n];
    if (value) node.textContent = value;
  });

  document.querySelectorAll("[data-i18n-attr]").forEach((node) => {
    node.dataset.i18nAttr.split(";").forEach((binding) => {
      const [attribute, key] = binding.split(":");
      const value = dictionary[key];
      if (attribute && value) node.setAttribute(attribute, value);
    });
  });

  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === lang);
    button.setAttribute("aria-pressed", String(button.dataset.lang === lang));
  });

  localStorage.setItem("oog-language", lang);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

const gatewayVisual = document.querySelector(".gateway-visual");
const gatewayScene = document.querySelector(".gateway-scene");
const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)");

if (gatewayVisual && gatewayScene) {
  gatewayVisual.addEventListener("pointermove", (event) => {
    if (reducedMotion.matches) return;
    const bounds = gatewayVisual.getBoundingClientRect();
    const x = (event.clientX - bounds.left) / bounds.width - 0.5;
    const y = (event.clientY - bounds.top) / bounds.height - 0.5;
    gatewayScene.style.setProperty("--tilt-x", `${61 - y * 8}deg`);
    gatewayScene.style.setProperty("--tilt-z", `${-9 + x * 10}deg`);
  });

  gatewayVisual.addEventListener("pointerleave", () => {
    gatewayScene.style.removeProperty("--tilt-x");
    gatewayScene.style.removeProperty("--tilt-z");
  });
}

applyLanguage(localStorage.getItem("oog-language") || "zh-Hant");
