const translations = {
  "zh-Hant": {
    "meta.description": "OPC Osaka Gateway 是大阪精品 OPC 公司與多產業事業的入口網站。",
    "nav.group": "集團",
    "nav.ventures": "事業",
    "nav.competitors": "競品",
    "nav.cases": "案例",
    "nav.systems": "系統",
    "nav.diary": "日記",
    "nav.contact": "下一步",
    "hero.eyebrow": "大阪精品 OPC 事業入口",
    "hero.lead": "為 OPC Osaka Group 建立清晰、具精品感的入口：連結多產業事業、AI 營運、市場研究與部署系統。",
    "hero.primary": "查看事業方向",
    "hero.secondary": "查看內部系統",
    "signal.baseLabel": "據點",
    "signal.base": "日本大阪",
    "signal.roleLabel": "角色",
    "signal.role": "集團入口",
    "signal.focusLabel": "重點",
    "signal.focus": "AI 原生營運",
    "group.eyebrow": "集團定位",
    "group.title": "以大阪為基地，建立跨產業的精品營運集團。",
    "group.body": "OOG 是未來大阪公司架構的公開入口：以一個母品牌承接多個產業專案，並共享策略、研究、自動化與數位部署的營運層。",
    "ventures.ai.title": "AI 營運",
    "ventures.ai.body": "代理人治理、訊號到行動流程，以及內部自動化模板。",
    "ventures.market.title": "市場情報",
    "ventures.market.body": "針對 CDP、客戶互動與意圖資料市場建立競品研究儀表板。",
    "ventures.education.title": "教育與人才",
    "ventures.education.body": "學校平台、招募流程、學生入口，以及跨境人才系統。",
    "ventures.commerce.title": "商務系統",
    "ventures.commerce.body": "庫存、加盟、餐飲服務，以及真實企業使用的輕量營運工具。",
    "cases.eyebrow": "已完成案例",
    "cases.title": "第一個完成案例：OOG 多語系入口網站。",
    "cases.intro": "這個案例證明 OOG 不只是概念，而是已經能完成從命名、內容整理、GitHub 版本管理到 Render 公開部署的完整流程。",
    "cases.case1.status": "已完成",
    "cases.case1.title": "OPC Osaka Gateway 官方入口",
    "cases.case1.body": "建立一個可供股東、合作夥伴與內部成員查看的公開網站，支援繁體中文、日文、簡體中文與英文，並透過 GitHub 與 Render 建立可持續更新的部署流程。",
    "cases.case1.scopeLabel": "範圍",
    "cases.case1.scope": "品牌入口、四語內容、公司日記、公開部署",
    "cases.case1.stackLabel": "工具",
    "cases.case1.resultLabel": "成果",
    "cases.case1.result": "形成可展示、可追蹤、可持續擴充的公司入口。",
    "cases.case2.status": "已確認四語上線",
    "cases.case2.title": "Exhibit Platform 展示平台",
    "cases.case2.body": "完成一個已上線的展示平台，並確認繁體中文、日文、簡體中文與英文四語版本可公開瀏覽。此案例可作為 OOG 對外展示多語系網站部署與營運能力的完成作品。",
    "cases.case2.scopeLabel": "範圍",
    "cases.case2.scope": "展示平台、四語上線、公開網址驗證",
    "cases.case2.linkLabel": "網址",
    "cases.case2.resultLabel": "成果",
    "cases.case2.result": "形成第二個可公開展示的完成案例。",
    "cases.case3.status": "已上線",
    "cases.case3.title": "Intex Osaka Exhibitions 展覽平台",
    "cases.case3.body": "建立以大阪展覽活動為主題的公開展示平台，並完成 Render 線上部署。此案例補足 OOG 在活動資訊、展覽導覽與地區型內容網站上的可交付能力。",
    "cases.case3.scopeLabel": "範圍",
    "cases.case3.scope": "大阪展覽資訊、公開展示頁、Render 部署驗證",
    "cases.case3.linkLabel": "網址",
    "cases.case3.resultLabel": "成果",
    "cases.case3.result": "形成第三個可公開展示的完成案例。",
    "cases.case4.status": "教學頁已上線 / 影片待補",
    "cases.case4.title": "Stock Bot 投資計畫教學",
    "cases.case4.body": "建立投資計畫教學入口，讓使用者可從繁體中文版本開始理解投資計畫流程、操作步驟與平台功能。目前頁面已公開上線，但教學影片尚未完成，後續需要補上影片腳本、錄製與嵌入。",
    "cases.case4.scopeLabel": "範圍",
    "cases.case4.scope": "投資計畫教學頁、繁中入口、Render 部署驗證、影片待補",
    "cases.case4.linkLabel": "網址",
    "cases.case4.resultLabel": "成果",
    "cases.case4.result": "形成第四個可公開展示的案例；影片完成後再升級為完整教學案例。",
    "systems.eyebrow": "內部系統",
    "systems.title": "從概念到可部署的公司基礎設施。",
    "systems.site": "供股東、合作夥伴與內部成員使用的公開入口。",
    "systems.deploy": "可重複使用的 GitHub、Render 與靜態研究頁部署流程。",
    "systems.research": "用於平台定位與策略判斷的競爭情報儀表板。",
    "diary.eyebrow": "建立日記",
    "diary.title": "把每一次決策、部署與定位修正留下紀錄。",
    "diary.intro": "OOG 的日記不是行銷文章，而是公司從零開始建立時的工作紀錄：命名、網站、部署、多語系、事業定位與下一步策略，都會在這裡逐步整理。",
    "diary.entry1.month": "2026 / 06",
    "diary.entry1.title": "OOG 入口網站完成第一階段上線。",
    "diary.entry1.body": "今天確認 OOG 作為 OPC Osaka Gateway 的公開入口，並完成 GitHub 與 Render 部署。網站已支援繁體中文、日文與簡體中文，方便股東、合作夥伴與未來大阪法人相關成員查看。這一階段的核心不是把公司包裝得很大，而是先建立一個可信、可持續更新、能承接後續事業資訊的乾淨入口。",
    "diary.entry1.point1": "完成 OOG 命名與公開網址。",
    "diary.entry1.point2": "建立 GitHub 到 Render 的部署流程。",
    "diary.entry1.point3": "確立大阪精品 OPC 公司、多產業事業與 AI 營運層的初步定位。",
    "contact.eyebrow": "下一步",
    "contact.title": "把這裡作為對外清楚、乾淨的公司入口。",
    "contact.body": "隨著 OPC Osaka Group 的架構逐步具體化，可將各事業、儀表板、股東頁面與內部工具集中放在這裡。"
  },
  ja: {
    "meta.description": "OPC Osaka Gateway は、大阪を拠点とするブティック型 OPC 企業と複数事業の入口サイトです。",
    "nav.group": "グループ",
    "nav.ventures": "事業",
    "nav.competitors": "競合",
    "nav.cases": "実績",
    "nav.systems": "システム",
    "nav.diary": "日記",
    "nav.contact": "次の一手",
    "hero.eyebrow": "大阪発ブティック OPC 事業ゲートウェイ",
    "hero.lead": "OPC Osaka Group のための、品位ある明快な入口。複数事業、AI オペレーション、市場調査、デプロイ基盤をひとつのハブにつなぎます。",
    "hero.primary": "事業領域を見る",
    "hero.secondary": "内部システムを見る",
    "signal.baseLabel": "拠点",
    "signal.base": "日本・大阪",
    "signal.roleLabel": "役割",
    "signal.role": "グループ入口",
    "signal.focusLabel": "重点",
    "signal.focus": "AI ネイティブ運営",
    "group.eyebrow": "グループ定位",
    "group.title": "大阪を拠点に、複数産業へ展開するブティック型運営グループを構築します。",
    "group.body": "OOG は、将来の大阪法人構造に向けた公開ゲートウェイです。ひとつの親ブランドの下で複数の産業プロジェクトを束ね、戦略、調査、自動化、デジタルデプロイを共通の運営層として整えます。",
    "ventures.ai.title": "AI オペレーション",
    "ventures.ai.body": "エージェント管理、シグナルから実行までのワークフロー、社内自動化テンプレート。",
    "ventures.market.title": "市場インテリジェンス",
    "ventures.market.body": "CDP、顧客エンゲージメント、インテントデータ市場に向けた競合調査ダッシュボード。",
    "ventures.education.title": "教育・人材",
    "ventures.education.body": "学校プラットフォーム、採用フロー、学生ポータル、越境人材システム。",
    "ventures.commerce.title": "商務システム",
    "ventures.commerce.body": "在庫、フランチャイズ、フードサービス、実店舗で使える軽量な運営ツール。",
    "cases.eyebrow": "完了事例",
    "cases.title": "最初の完了事例：OOG 多言語ゲートウェイサイト。",
    "cases.intro": "この事例は、OOG が単なる構想ではなく、名称設計、コンテンツ整理、GitHub でのバージョン管理、Render での公開デプロイまでを一貫して実行できることを示しています。",
    "cases.case1.status": "完了",
    "cases.case1.title": "OPC Osaka Gateway 公式入口",
    "cases.case1.body": "株主、パートナー、社内メンバーが確認できる公開サイトを構築。繁体字中国語、日本語、簡体字中国語、英語に対応し、GitHub と Render による継続更新可能なデプロイ手順を整えました。",
    "cases.case1.scopeLabel": "範囲",
    "cases.case1.scope": "ブランド入口、4言語コンテンツ、会社日記、公開デプロイ",
    "cases.case1.stackLabel": "ツール",
    "cases.case1.resultLabel": "成果",
    "cases.case1.result": "表示、追跡、継続拡張ができる会社の入口を形成。",
    "cases.case2.status": "4言語公開確認済み",
    "cases.case2.title": "Exhibit Platform 展示プラットフォーム",
    "cases.case2.body": "公開済みの展示プラットフォームを完成し、繁体字中国語、日本語、簡体字中国語、英語の4言語版が閲覧できることを確認しました。OOG が多言語サイトのデプロイと運営能力を対外的に示す完成事例です。",
    "cases.case2.scopeLabel": "範囲",
    "cases.case2.scope": "展示プラットフォーム、4言語公開、公開URL確認",
    "cases.case2.linkLabel": "URL",
    "cases.case2.resultLabel": "成果",
    "cases.case2.result": "公開表示できる2つ目の完了事例を形成。",
    "cases.case3.status": "公開済み",
    "cases.case3.title": "Intex Osaka Exhibitions 展示プラットフォーム",
    "cases.case3.body": "大阪の展示会・イベント情報をテーマにした公開展示プラットフォームを構築し、Render でのオンラインデプロイを完了しました。OOG がイベント情報、展示会ナビゲーション、地域型コンテンツサイトを納品できることを示す事例です。",
    "cases.case3.scopeLabel": "範囲",
    "cases.case3.scope": "大阪展示会情報、公開展示ページ、Render デプロイ確認",
    "cases.case3.linkLabel": "URL",
    "cases.case3.resultLabel": "成果",
    "cases.case3.result": "公開表示できる3つ目の完了事例を形成。",
    "cases.case4.status": "ページ公開済み / 動画未完了",
    "cases.case4.title": "Stock Bot 投資計画チュートリアル",
    "cases.case4.body": "投資計画チュートリアルの入口を構築し、ユーザーが繁体字中国語版から投資計画の流れ、操作手順、プラットフォーム機能を理解できるようにしました。ページは公開済みですが、チュートリアル動画は未完了で、今後は動画台本、録画、埋め込みが必要です。",
    "cases.case4.scopeLabel": "範囲",
    "cases.case4.scope": "投資計画チュートリアルページ、繁体字中国語入口、Render デプロイ確認、動画未完了",
    "cases.case4.linkLabel": "URL",
    "cases.case4.resultLabel": "成果",
    "cases.case4.result": "公開表示できる4つ目の事例を形成。動画完了後に完全なチュートリアル事例へ更新。",
    "systems.eyebrow": "内部システム",
    "systems.title": "構想から、デプロイ可能な会社インフラへ。",
    "systems.site": "株主、パートナー、社内メンバーのための公開ゲートウェイ。",
    "systems.deploy": "GitHub、Render、静的リサーチページ向けの再利用可能なデプロイ手順。",
    "systems.research": "プラットフォームの定位と戦略判断に使う競争情報ダッシュボード。",
    "diary.eyebrow": "構築日記",
    "diary.title": "意思決定、デプロイ、定位の修正を一つずつ記録します。",
    "diary.intro": "OOG の日記はマーケティング記事ではなく、会社をゼロから作るための作業記録です。名称、ウェブサイト、デプロイ、多言語対応、事業定位、次の戦略をここに整理していきます。",
    "diary.entry1.month": "2026 / 06",
    "diary.entry1.title": "OOG ゲートウェイサイトの第一段階を公開しました。",
    "diary.entry1.body": "本日、OOG を OPC Osaka Gateway の公開入口として確認し、GitHub と Render でのデプロイを完了しました。サイトは繁体字中国語、日本語、簡体字中国語に対応し、株主、パートナー、将来の大阪法人に関わるメンバーが確認しやすい形になっています。この段階の中心は、会社を大きく見せることではなく、信頼でき、継続的に更新でき、次の事業情報を受け止められる整った入口を作ることです。",
    "diary.entry1.point1": "OOG の名称と公開 URL を確定。",
    "diary.entry1.point2": "GitHub から Render へのデプロイ手順を構築。",
    "diary.entry1.point3": "大阪発ブティック OPC 企業、複数事業、AI 運営層の初期定位を整理。",
    "contact.eyebrow": "次の一手",
    "contact.title": "ここを、対外的に明快で整った会社の玄関口にします。",
    "contact.body": "OPC Osaka Group の構造が具体化するにつれ、各事業、ダッシュボード、株主向けページ、社内ツールをここに集約できます。"
  },
  "zh-Hans": {
    "meta.description": "OPC Osaka Gateway 是大阪精品 OPC 公司与多产业事业的入口网站。",
    "nav.group": "集团",
    "nav.ventures": "事业",
    "nav.competitors": "竞品",
    "nav.cases": "案例",
    "nav.systems": "系统",
    "nav.diary": "日记",
    "nav.contact": "下一步",
    "hero.eyebrow": "大阪精品 OPC 事业入口",
    "hero.lead": "为 OPC Osaka Group 建立清晰、具精品感的入口：连接多产业事业、AI 运营、市场研究与部署系统。",
    "hero.primary": "查看事业方向",
    "hero.secondary": "查看内部系统",
    "signal.baseLabel": "据点",
    "signal.base": "日本大阪",
    "signal.roleLabel": "角色",
    "signal.role": "集团入口",
    "signal.focusLabel": "重点",
    "signal.focus": "AI 原生运营",
    "group.eyebrow": "集团定位",
    "group.title": "以大阪为基地，建立跨产业的精品运营集团。",
    "group.body": "OOG 是未来大阪公司架构的公开入口：以一个母品牌承接多个产业项目，并共享策略、研究、自动化与数字部署的运营层。",
    "ventures.ai.title": "AI 运营",
    "ventures.ai.body": "代理人治理、信号到行动流程，以及内部自动化模板。",
    "ventures.market.title": "市场情报",
    "ventures.market.body": "针对 CDP、客户互动与意图数据市场建立竞品研究仪表板。",
    "ventures.education.title": "教育与人才",
    "ventures.education.body": "学校平台、招聘流程、学生入口，以及跨境人才系统。",
    "ventures.commerce.title": "商务系统",
    "ventures.commerce.body": "库存、加盟、餐饮服务，以及真实企业使用的轻量运营工具。",
    "cases.eyebrow": "已完成案例",
    "cases.title": "第一个完成案例：OOG 多语言入口网站。",
    "cases.intro": "这个案例证明 OOG 不只是概念，而是已经能完成从命名、内容整理、GitHub 版本管理到 Render 公开部署的完整流程。",
    "cases.case1.status": "已完成",
    "cases.case1.title": "OPC Osaka Gateway 官方入口",
    "cases.case1.body": "建立一个可供股东、合作伙伴与内部成员查看的公开网站，支持繁体中文、日文、简体中文与英文，并通过 GitHub 与 Render 建立可持续更新的部署流程。",
    "cases.case1.scopeLabel": "范围",
    "cases.case1.scope": "品牌入口、四语内容、公司日记、公开部署",
    "cases.case1.stackLabel": "工具",
    "cases.case1.resultLabel": "成果",
    "cases.case1.result": "形成可展示、可追踪、可持续扩充的公司入口。",
    "cases.case2.status": "已确认四语上线",
    "cases.case2.title": "Exhibit Platform 展示平台",
    "cases.case2.body": "完成一个已上线的展示平台，并确认繁体中文、日文、简体中文与英文四语版本可公开浏览。此案例可作为 OOG 对外展示多语言网站部署与运营能力的完成作品。",
    "cases.case2.scopeLabel": "范围",
    "cases.case2.scope": "展示平台、四语上线、公开网址验证",
    "cases.case2.linkLabel": "网址",
    "cases.case2.resultLabel": "成果",
    "cases.case2.result": "形成第二个可公开展示的完成案例。",
    "cases.case3.status": "已上线",
    "cases.case3.title": "Intex Osaka Exhibitions 展览平台",
    "cases.case3.body": "建立以大阪展览活动为主题的公开展示平台，并完成 Render 线上部署。此案例补足 OOG 在活动信息、展览导览与地区型内容网站上的交付能力。",
    "cases.case3.scopeLabel": "范围",
    "cases.case3.scope": "大阪展览信息、公开展示页、Render 部署验证",
    "cases.case3.linkLabel": "网址",
    "cases.case3.resultLabel": "成果",
    "cases.case3.result": "形成第三个可公开展示的完成案例。",
    "cases.case4.status": "教学页已上线 / 视频待补",
    "cases.case4.title": "Stock Bot 投资计划教学",
    "cases.case4.body": "建立投资计划教学入口，让使用者可从繁体中文版本开始理解投资计划流程、操作步骤与平台功能。目前页面已公开上线，但教学视频尚未完成，后续需要补上视频脚本、录制与嵌入。",
    "cases.case4.scopeLabel": "范围",
    "cases.case4.scope": "投资计划教学页、繁中入口、Render 部署验证、视频待补",
    "cases.case4.linkLabel": "网址",
    "cases.case4.resultLabel": "成果",
    "cases.case4.result": "形成第四个可公开展示的案例；视频完成后再升级为完整教学案例。",
    "systems.eyebrow": "内部系统",
    "systems.title": "从概念到可部署的公司基础设施。",
    "systems.site": "供股东、合作伙伴与内部成员使用的公开入口。",
    "systems.deploy": "可重复使用的 GitHub、Render 与静态研究页部署流程。",
    "systems.research": "用于平台定位与策略判断的竞争情报仪表板。",
    "diary.eyebrow": "建立日记",
    "diary.title": "把每一次决策、部署与定位修正留下记录。",
    "diary.intro": "OOG 的日记不是营销文章，而是公司从零开始建立时的工作记录：命名、网站、部署、多语言、事业定位与下一步策略，都会在这里逐步整理。",
    "diary.entry1.month": "2026 / 06",
    "diary.entry1.title": "OOG 入口网站完成第一阶段上线。",
    "diary.entry1.body": "今天确认 OOG 作为 OPC Osaka Gateway 的公开入口，并完成 GitHub 与 Render 部署。网站已支持繁体中文、日文与简体中文，方便股东、合作伙伴与未来大阪法人相关成员查看。这一阶段的核心不是把公司包装得很大，而是先建立一个可信、可持续更新、能承接后续事业信息的干净入口。",
    "diary.entry1.point1": "完成 OOG 命名与公开网址。",
    "diary.entry1.point2": "建立 GitHub 到 Render 的部署流程。",
    "diary.entry1.point3": "确立大阪精品 OPC 公司、多产业事业与 AI 运营层的初步定位。",
    "contact.eyebrow": "下一步",
    "contact.title": "把这里作为对外清楚、干净的公司入口。",
    "contact.body": "随着 OPC Osaka Group 的架构逐步具体化，可将各事业、仪表板、股东页面与内部工具集中放在这里。"
  },
  en: {
    "meta.description": "OPC Osaka Gateway is the entry site for a boutique Osaka OPC company and multi-industry ventures.",
    "nav.group": "Group",
    "nav.ventures": "Ventures",
    "nav.competitors": "Competitors",
    "nav.cases": "Cases",
    "nav.systems": "Systems",
    "nav.diary": "Diary",
    "nav.contact": "Next",
    "hero.eyebrow": "Osaka boutique OPC venture gateway",
    "hero.lead": "A clear, refined entry point for OPC Osaka Group: connecting multi-industry ventures, AI operations, market research, and deployment systems.",
    "hero.primary": "Explore ventures",
    "hero.secondary": "View systems",
    "signal.baseLabel": "Base",
    "signal.base": "Osaka, Japan",
    "signal.roleLabel": "Role",
    "signal.role": "Group gateway",
    "signal.focusLabel": "Focus",
    "signal.focus": "AI-native operations",
    "group.eyebrow": "Group positioning",
    "group.title": "A boutique operating group built in Osaka for multiple industries.",
    "group.body": "OOG is the public doorway for a future Osaka company structure: one parent identity, multiple industry projects, and a shared operating layer for strategy, research, automation, and digital deployment.",
    "ventures.ai.title": "AI Operations",
    "ventures.ai.body": "Agent governance, signal-to-action workflows, and internal automation templates.",
    "ventures.market.title": "Market Intelligence",
    "ventures.market.body": "Competitive research dashboards for CDP, customer engagement, and intent data markets.",
    "ventures.education.title": "Education & Talent",
    "ventures.education.body": "School platforms, hiring workflows, student portals, and cross-border talent systems.",
    "ventures.commerce.title": "Commerce Systems",
    "ventures.commerce.body": "Inventory, franchise, food-service, and lightweight operating tools for real businesses.",
    "cases.eyebrow": "Completed case",
    "cases.title": "First completed case: the OOG multilingual gateway site.",
    "cases.intro": "This case shows that OOG is not only a concept. It can already complete the full workflow from naming, content organization, GitHub version control, and public Render deployment.",
    "cases.case1.status": "Completed",
    "cases.case1.title": "OPC Osaka Gateway official entry site",
    "cases.case1.body": "A public website for shareholders, partners, and internal members, supporting Traditional Chinese, Japanese, Simplified Chinese, and English, with a sustainable GitHub-to-Render deployment flow.",
    "cases.case1.scopeLabel": "Scope",
    "cases.case1.scope": "Brand gateway, four-language content, company diary, public deployment",
    "cases.case1.stackLabel": "Stack",
    "cases.case1.resultLabel": "Result",
    "cases.case1.result": "A presentable, trackable, continuously expandable company gateway.",
    "cases.case2.status": "Four languages verified",
    "cases.case2.title": "Exhibit Platform",
    "cases.case2.body": "A live exhibit platform with Traditional Chinese, Japanese, Simplified Chinese, and English confirmed publicly available. This case demonstrates OOG's ability to deploy and operate multilingual websites as finished public work.",
    "cases.case2.scopeLabel": "Scope",
    "cases.case2.scope": "Exhibit platform, four-language launch, public URL verification",
    "cases.case2.linkLabel": "URL",
    "cases.case2.resultLabel": "Result",
    "cases.case2.result": "A second completed case that can be shared publicly.",
    "cases.case3.status": "Live",
    "cases.case3.title": "Intex Osaka Exhibitions platform",
    "cases.case3.body": "A public exhibit platform focused on Osaka exhibition activity, deployed live on Render. This case strengthens OOG's delivery record for event information, exhibition navigation, and local content websites.",
    "cases.case3.scopeLabel": "Scope",
    "cases.case3.scope": "Osaka exhibition information, public exhibit page, Render deployment verification",
    "cases.case3.linkLabel": "URL",
    "cases.case3.resultLabel": "Result",
    "cases.case3.result": "A third completed case that can be shared publicly.",
    "cases.case4.status": "Page live / video pending",
    "cases.case4.title": "Stock Bot investment plan tutorial",
    "cases.case4.body": "A tutorial entry point for investment plans, allowing users to start from the Traditional Chinese version and understand the plan flow, operating steps, and platform features. The page is live, but the tutorial video is not complete yet; the next work is script writing, recording, and embedding.",
    "cases.case4.scopeLabel": "Scope",
    "cases.case4.scope": "Investment plan tutorial page, Traditional Chinese entry, Render deployment verification, video pending",
    "cases.case4.linkLabel": "URL",
    "cases.case4.resultLabel": "Result",
    "cases.case4.result": "A fourth public case is available; it will become a complete tutorial case after the video is finished.",
    "systems.eyebrow": "Internal systems",
    "systems.title": "From concept to deployable company infrastructure.",
    "systems.site": "A public gateway for shareholders, partners, and internal navigation.",
    "systems.deploy": "A repeatable deployment flow for GitHub, Render, and static research pages.",
    "systems.research": "A competitive intelligence dashboard for platform positioning and strategy.",
    "diary.eyebrow": "Build diary",
    "diary.title": "Recording each decision, deployment, and positioning adjustment.",
    "diary.intro": "The OOG diary is not marketing copy. It is a working record of building the company from zero: naming, website, deployment, multilingual content, venture positioning, and next-step strategy will be organized here over time.",
    "diary.entry1.month": "2026 / 06",
    "diary.entry1.title": "The first stage of the OOG gateway site is live.",
    "diary.entry1.body": "Today we confirmed OOG as the public gateway for OPC Osaka Gateway and completed the GitHub and Render deployment. The site now supports Traditional Chinese, Japanese, Simplified Chinese, and English, making it easier for shareholders, partners, and future Osaka company members to review. The goal at this stage is not to make the company look oversized, but to establish a credible, clean, continuously updateable front door that can hold future venture information.",
    "diary.entry1.point1": "Confirmed the OOG name and public URL.",
    "diary.entry1.point2": "Built the GitHub-to-Render deployment flow.",
    "diary.entry1.point3": "Clarified the initial positioning for an Osaka boutique OPC company, multi-industry ventures, and an AI operations layer.",
    "contact.eyebrow": "Next step",
    "contact.title": "Use this as the clear public front door for the company.",
    "contact.body": "As the OPC Osaka Group structure becomes more concrete, each venture, dashboard, shareholder page, and internal tool can be gathered here."
  }
};

function applyLanguage(lang) {
  const dictionary = translations[lang] || translations["zh-Hant"];

  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const value = dictionary[node.dataset.i18n];
    if (value) node.textContent = value;
  });

  document.querySelectorAll("[data-i18n-attr]").forEach((node) => {
    node.dataset.i18nAttr.split(";").forEach((binding) => {
      const [attribute, key] = binding.split(":");
      const value = dictionary[key];
      if (attribute && value) node.setAttribute(attribute, value);
    });
  });

  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === lang);
    button.setAttribute("aria-pressed", String(button.dataset.lang === lang));
  });

  localStorage.setItem("oog-language", lang);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

applyLanguage(localStorage.getItem("oog-language") || "zh-Hant");
